// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/tmdb/client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/tmdb/client.go -destination=pkg/tmdb/client_mock.go -package=tmdb
//

// Package tmdb is a generated GoMock package.
package tmdb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchMovieDetails mocks base method.
func (m *MockClient) FetchMovieDetails(ctx context.Context, id uint64) (*MovieDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMovieDetails", ctx, id)
	ret0, _ := ret[0].(*MovieDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMovieDetails indicates an expected call of FetchMovieDetails.
func (mr *MockClientMockRecorder) FetchMovieDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMovieDetails", reflect.TypeOf((*MockClient)(nil).FetchMovieDetails), ctx, id)
}

// FetchPersonDetails mocks base method.
func (m *MockClient) FetchPersonDetails(ctx context.Context, id uint64) (*PersonDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPersonDetails", ctx, id)
	ret0, _ := ret[0].(*PersonDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPersonDetails indicates an expected call of FetchPersonDetails.
func (mr *MockClientMockRecorder) FetchPersonDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPersonDetails", reflect.TypeOf((*MockClient)(nil).FetchPersonDetails), ctx, id)
}

// FetchTrendingMovies mocks base method.
func (m *MockClient) FetchTrendingMovies(ctx context.Context) (*MovieListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTrendingMovies", ctx)
	ret0, _ := ret[0].(*MovieListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTrendingMovies indicates an expected call of FetchTrendingMovies.
func (mr *MockClientMockRecorder) FetchTrendingMovies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTrendingMovies", reflect.TypeOf((*MockClient)(nil).FetchTrendingMovies), ctx)
}

// FetchTrendingPeople mocks base method.
func (m *MockClient) FetchTrendingPeople(ctx context.Context) (*PersonListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTrendingPeople", ctx)
	ret0, _ := ret[0].(*PersonListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTrendingPeople indicates an expected call of FetchTrendingPeople.
func (mr *MockClientMockRecorder) FetchTrendingPeople(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTrendingPeople", reflect.TypeOf((*MockClient)(nil).FetchTrendingPeople), ctx)
}

// FetchTrendingTv mocks base method.
func (m *MockClient) FetchTrendingTv(ctx context.Context) (*TvListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTrendingTv", ctx)
	ret0, _ := ret[0].(*TvListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTrendingTv indicates an expected call of FetchTrendingTv.
func (mr *MockClientMockRecorder) FetchTrendingTv(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTrendingTv", reflect.TypeOf((*MockClient)(nil).FetchTrendingTv), ctx)
}

// FetchTvDetails mocks base method.
func (m *MockClient) FetchTvDetails(ctx context.Context, id uint64) (*TvDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTvDetails", ctx, id)
	ret0, _ := ret[0].(*TvDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTvDetails indicates an expected call of FetchTvDetails.
func (mr *MockClientMockRecorder) FetchTvDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTvDetails", reflect.TypeOf((*MockClient)(nil).FetchTvDetails), ctx, id)
}

// FetchTvEpisodeDetails mocks base method.
func (m *MockClient) FetchTvEpisodeDetails(ctx context.Context, id, seasonNumber, episodeNumber uint64) (*EpisodeDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTvEpisodeDetails", ctx, id, seasonNumber, episodeNumber)
	ret0, _ := ret[0].(*EpisodeDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTvEpisodeDetails indicates an expected call of FetchTvEpisodeDetails.
func (mr *MockClientMockRecorder) FetchTvEpisodeDetails(ctx, id, seasonNumber, episodeNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTvEpisodeDetails", reflect.TypeOf((*MockClient)(nil).FetchTvEpisodeDetails), ctx, id, seasonNumber, episodeNumber)
}

// FetchTvSeasonDetails mocks base method.
func (m *MockClient) FetchTvSeasonDetails(ctx context.Context, id, seasonNumber uint64) (*SeasonDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTvSeasonDetails", ctx, id, seasonNumber)
	ret0, _ := ret[0].(*SeasonDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTvSeasonDetails indicates an expected call of FetchTvSeasonDetails.
func (mr *MockClientMockRecorder) FetchTvSeasonDetails(ctx, id, seasonNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTvSeasonDetails", reflect.TypeOf((*MockClient)(nil).FetchTvSeasonDetails), ctx, id, seasonNumber)
}

// Find mocks base method.
func (m *MockClient) Find(ctx context.Context, externalId, source string) (*FindResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, externalId, source)
	ret0, _ := ret[0].(*FindResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockClientMockRecorder) Find(ctx, externalId, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockClient)(nil).Find), ctx, externalId, source)
}

// SearchMovies mocks base method.
func (m *MockClient) SearchMovies(ctx context.Context, query string, page uint64) (*MovieListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMovies", ctx, query, page)
	ret0, _ := ret[0].(*MovieListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovies indicates an expected call of SearchMovies.
func (mr *MockClientMockRecorder) SearchMovies(ctx, query, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovies", reflect.TypeOf((*MockClient)(nil).SearchMovies), ctx, query, page)
}

// SearchPeople mocks base method.
func (m *MockClient) SearchPeople(ctx context.Context, query string, page uint64) (*PersonListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPeople", ctx, query, page)
	ret0, _ := ret[0].(*PersonListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPeople indicates an expected call of SearchPeople.
func (mr *MockClientMockRecorder) SearchPeople(ctx, query, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPeople", reflect.TypeOf((*MockClient)(nil).SearchPeople), ctx, query, page)
}

// SearchTv mocks base method.
func (m *MockClient) SearchTv(ctx context.Context, query string, page uint64) (*TvListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTv", ctx, query, page)
	ret0, _ := ret[0].(*TvListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTv indicates an expected call of SearchTv.
func (mr *MockClientMockRecorder) SearchTv(ctx, query, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTv", reflect.TypeOf((*MockClient)(nil).SearchTv), ctx, query, page)
}
