// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/igdb/client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/igdb/client.go -destination=pkg/igdb/client_mock.go -package=igdb
//

// Package igdb is a generated GoMock package.
package igdb

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchGameDetails mocks base method.
func (m *MockClient) FetchGameDetails(ctx context.Context, id uint64) (*GameDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGameDetails", ctx, id)
	ret0, _ := ret[0].(*GameDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGameDetails indicates an expected call of FetchGameDetails.
func (mr *MockClientMockRecorder) FetchGameDetails(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGameDetails", reflect.TypeOf((*MockClient)(nil).FetchGameDetails), ctx, id)
}

// FetchTrendingGames mocks base method.
func (m *MockClient) FetchTrendingGames(ctx context.Context, limit uint64) (*GameListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTrendingGames", ctx, limit)
	ret0, _ := ret[0].(*GameListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTrendingGames indicates an expected call of FetchTrendingGames.
func (mr *MockClientMockRecorder) FetchTrendingGames(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTrendingGames", reflect.TypeOf((*MockClient)(nil).FetchTrendingGames), ctx, limit)
}

// SearchGames mocks base method.
func (m *MockClient) SearchGames(ctx context.Context, query string, limit, offset uint64) (*GameListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchGames", ctx, query, limit, offset)
	ret0, _ := ret[0].(*GameListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchGames indicates an expected call of SearchGames.
func (mr *MockClientMockRecorder) SearchGames(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchGames", reflect.TypeOf((*MockClient)(nil).SearchGames), ctx, query, limit, offset)
}
