// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repositories/games.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/repositories/games.go -destination=internal/app/repositories/games_mock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGameRepository is a mock of GameRepository interface.
type MockGameRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameRepositoryMockRecorder
	isgomock struct{}
}

// MockGameRepositoryMockRecorder is the mock recorder for MockGameRepository.
type MockGameRepositoryMockRecorder struct {
	mock *MockGameRepository
}

// NewMockGameRepository creates a new mock instance.
func NewMockGameRepository(ctrl *gomock.Controller) *MockGameRepository {
	mock := &MockGameRepository{ctrl: ctrl}
	mock.recorder = &MockGameRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameRepository) EXPECT() *MockGameRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGameRepository) Create(ctx context.Context, params *models.Game) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGameRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameRepository)(nil).Create), ctx, params)
}

// DeleteByIgdbId mocks base method.
func (m *MockGameRepository) DeleteByIgdbId(ctx context.Context, igdbId uint64, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIgdbId", ctx, igdbId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIgdbId indicates an expected call of DeleteByIgdbId.
func (mr *MockGameRepositoryMockRecorder) DeleteByIgdbId(ctx, igdbId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIgdbId", reflect.TypeOf((*MockGameRepository)(nil).DeleteByIgdbId), ctx, igdbId, userId)
}

// FindByIgdbId mocks base method.
func (m *MockGameRepository) FindByIgdbId(ctx context.Context, igdbId uint64, userId uuid.UUID) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIgdbId", ctx, igdbId, userId)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIgdbId indicates an expected call of FindByIgdbId.
func (mr *MockGameRepositoryMockRecorder) FindByIgdbId(ctx, igdbId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIgdbId", reflect.TypeOf((*MockGameRepository)(nil).FindByIgdbId), ctx, igdbId, userId)
}

// FindGamesByIgdbIds mocks base method.
func (m *MockGameRepository) FindGamesByIgdbIds(ctx context.Context, igdbIds []uint64, userId uuid.UUID) ([]models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGamesByIgdbIds", ctx, igdbIds, userId)
	ret0, _ := ret[0].([]models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGamesByIgdbIds indicates an expected call of FindGamesByIgdbIds.
func (mr *MockGameRepositoryMockRecorder) FindGamesByIgdbIds(ctx, igdbIds, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGamesByIgdbIds", reflect.TypeOf((*MockGameRepository)(nil).FindGamesByIgdbIds), ctx, igdbIds, userId)
}

// List mocks base method.
func (m *MockGameRepository) List(ctx context.Context, userId uuid.UUID, state models.StateType, limit, offset uint64) ([]models.Game, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userId, state, limit, offset)
	ret0, _ := ret[0].([]models.Game)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockGameRepositoryMockRecorder) List(ctx, userId, state, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGameRepository)(nil).List), ctx, userId, state, limit, offset)
}

// Update mocks base method.
func (m *MockGameRepository) Update(ctx context.Context, params *models.Game) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGameRepositoryMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameRepository)(nil).Update), ctx, params)
}

// UpdateByIgdbId mocks base method.
func (m *MockGameRepository) UpdateByIgdbId(ctx context.Context, params *models.Game) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByIgdbId", ctx, params)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByIgdbId indicates an expected call of UpdateByIgdbId.
func (mr *MockGameRepositoryMockRecorder) UpdateByIgdbId(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByIgdbId", reflect.TypeOf((*MockGameRepository)(nil).UpdateByIgdbId), ctx, params)
}
