// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repositories/integrations.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/repositories/integrations.go -destination=internal/app/repositories/integrations_mock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIntegrationRepository is a mock of IntegrationRepository interface.
type MockIntegrationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationRepositoryMockRecorder
	isgomock struct{}
}

// MockIntegrationRepositoryMockRecorder is the mock recorder for MockIntegrationRepository.
type MockIntegrationRepositoryMockRecorder struct {
	mock *MockIntegrationRepository
}

// NewMockIntegrationRepository creates a new mock instance.
func NewMockIntegrationRepository(ctrl *gomock.Controller) *MockIntegrationRepository {
	mock := &MockIntegrationRepository{ctrl: ctrl}
	mock.recorder = &MockIntegrationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegrationRepository) EXPECT() *MockIntegrationRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIntegrationRepository) Delete(ctx context.Context, userId uuid.UUID, provider string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userId, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIntegrationRepositoryMockRecorder) Delete(ctx, userId, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIntegrationRepository)(nil).Delete), ctx, userId, provider)
}

// FindByTokenHash mocks base method.
func (m *MockIntegrationRepository) FindByTokenHash(ctx context.Context, hash, provider string) (*models.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTokenHash", ctx, hash, provider)
	ret0, _ := ret[0].(*models.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTokenHash indicates an expected call of FindByTokenHash.
func (mr *MockIntegrationRepositoryMockRecorder) FindByTokenHash(ctx, hash, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTokenHash", reflect.TypeOf((*MockIntegrationRepository)(nil).FindByTokenHash), ctx, hash, provider)
}

// Upsert mocks base method.
func (m *MockIntegrationRepository) Upsert(ctx context.Context, params *models.Integration) (*models.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, params)
	ret0, _ := ret[0].(*models.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockIntegrationRepositoryMockRecorder) Upsert(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockIntegrationRepository)(nil).Upsert), ctx, params)
}
