// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repositories/progress.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/repositories/progress.go -destination=internal/app/repositories/progress_mock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSeriesProgressRepository is a mock of SeriesProgressRepository interface.
type MockSeriesProgressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeriesProgressRepositoryMockRecorder
	isgomock struct{}
}

// MockSeriesProgressRepositoryMockRecorder is the mock recorder for MockSeriesProgressRepository.
type MockSeriesProgressRepositoryMockRecorder struct {
	mock *MockSeriesProgressRepository
}

// NewMockSeriesProgressRepository creates a new mock instance.
func NewMockSeriesProgressRepository(ctrl *gomock.Controller) *MockSeriesProgressRepository {
	mock := &MockSeriesProgressRepository{ctrl: ctrl}
	mock.recorder = &MockSeriesProgressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeriesProgressRepository) EXPECT() *MockSeriesProgressRepositoryMockRecorder {
	return m.recorder
}

// MarkEpisodeWatched mocks base method.
func (m *MockSeriesProgressRepository) MarkEpisodeWatched(ctx context.Context, userId uuid.UUID, series models.SeriesInput, season models.SeasonInput, episode models.EpisodeInput) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEpisodeWatched", ctx, userId, series, season, episode)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEpisodeWatched indicates an expected call of MarkEpisodeWatched.
func (mr *MockSeriesProgressRepositoryMockRecorder) MarkEpisodeWatched(ctx, userId, series, season, episode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEpisodeWatched", reflect.TypeOf((*MockSeriesProgressRepository)(nil).MarkEpisodeWatched), ctx, userId, series, season, episode)
}

// MarkSeasonWatched mocks base method.
func (m *MockSeriesProgressRepository) MarkSeasonWatched(ctx context.Context, userId uuid.UUID, series models.SeriesInput, season models.SeasonInput) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSeasonWatched", ctx, userId, series, season)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkSeasonWatched indicates an expected call of MarkSeasonWatched.
func (mr *MockSeriesProgressRepositoryMockRecorder) MarkSeasonWatched(ctx, userId, series, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSeasonWatched", reflect.TypeOf((*MockSeriesProgressRepository)(nil).MarkSeasonWatched), ctx, userId, series, season)
}

// MarkShowWatched mocks base method.
func (m *MockSeriesProgressRepository) MarkShowWatched(ctx context.Context, userId uuid.UUID, show models.ShowInput) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkShowWatched", ctx, userId, show)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkShowWatched indicates an expected call of MarkShowWatched.
func (mr *MockSeriesProgressRepositoryMockRecorder) MarkShowWatched(ctx, userId, show any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkShowWatched", reflect.TypeOf((*MockSeriesProgressRepository)(nil).MarkShowWatched), ctx, userId, show)
}

// Progress mocks base method.
func (m *MockSeriesProgressRepository) Progress(ctx context.Context, userId uuid.UUID, seriesTmdbId uint64) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Progress", ctx, userId, seriesTmdbId)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Progress indicates an expected call of Progress.
func (mr *MockSeriesProgressRepositoryMockRecorder) Progress(ctx, userId, seriesTmdbId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Progress", reflect.TypeOf((*MockSeriesProgressRepository)(nil).Progress), ctx, userId, seriesTmdbId)
}

// UnmarkEpisodeWatched mocks base method.
func (m *MockSeriesProgressRepository) UnmarkEpisodeWatched(ctx context.Context, userId uuid.UUID, seriesTmdbId, seasonTmdbId, episodeTmdbId uint64) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarkEpisodeWatched", ctx, userId, seriesTmdbId, seasonTmdbId, episodeTmdbId)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarkEpisodeWatched indicates an expected call of UnmarkEpisodeWatched.
func (mr *MockSeriesProgressRepositoryMockRecorder) UnmarkEpisodeWatched(ctx, userId, seriesTmdbId, seasonTmdbId, episodeTmdbId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarkEpisodeWatched", reflect.TypeOf((*MockSeriesProgressRepository)(nil).UnmarkEpisodeWatched), ctx, userId, seriesTmdbId, seasonTmdbId, episodeTmdbId)
}

// UnmarkSeasonWatched mocks base method.
func (m *MockSeriesProgressRepository) UnmarkSeasonWatched(ctx context.Context, userId uuid.UUID, seriesTmdbId, seasonTmdbId uint64) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarkSeasonWatched", ctx, userId, seriesTmdbId, seasonTmdbId)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarkSeasonWatched indicates an expected call of UnmarkSeasonWatched.
func (mr *MockSeriesProgressRepositoryMockRecorder) UnmarkSeasonWatched(ctx, userId, seriesTmdbId, seasonTmdbId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarkSeasonWatched", reflect.TypeOf((*MockSeriesProgressRepository)(nil).UnmarkSeasonWatched), ctx, userId, seriesTmdbId, seasonTmdbId)
}

// UnmarkShowWatched mocks base method.
func (m *MockSeriesProgressRepository) UnmarkShowWatched(ctx context.Context, userId uuid.UUID, seriesTmdbId uint64) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarkShowWatched", ctx, userId, seriesTmdbId)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarkShowWatched indicates an expected call of UnmarkShowWatched.
func (mr *MockSeriesProgressRepositoryMockRecorder) UnmarkShowWatched(ctx, userId, seriesTmdbId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarkShowWatched", reflect.TypeOf((*MockSeriesProgressRepository)(nil).UnmarkShowWatched), ctx, userId, seriesTmdbId)
}
