// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repositories/series.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/repositories/series.go -destination=internal/app/repositories/series_mock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSeriesRepository is a mock of SeriesRepository interface.
type MockSeriesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeriesRepositoryMockRecorder
	isgomock struct{}
}

// MockSeriesRepositoryMockRecorder is the mock recorder for MockSeriesRepository.
type MockSeriesRepositoryMockRecorder struct {
	mock *MockSeriesRepository
}

// NewMockSeriesRepository creates a new mock instance.
func NewMockSeriesRepository(ctrl *gomock.Controller) *MockSeriesRepository {
	mock := &MockSeriesRepository{ctrl: ctrl}
	mock.recorder = &MockSeriesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeriesRepository) EXPECT() *MockSeriesRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSeriesRepository) Create(ctx context.Context, params *models.Series) (*models.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*models.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSeriesRepositoryMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSeriesRepository)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockSeriesRepository) Delete(ctx context.Context, tmdbId uint64, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tmdbId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSeriesRepositoryMockRecorder) Delete(ctx, tmdbId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSeriesRepository)(nil).Delete), ctx, tmdbId, userId)
}

// FindByFilter mocks base method.
func (m *MockSeriesRepository) FindByFilter(ctx context.Context, filter models.SeriesFilter) ([]models.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", ctx, filter)
	ret0, _ := ret[0].([]models.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockSeriesRepositoryMockRecorder) FindByFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockSeriesRepository)(nil).FindByFilter), ctx, filter)
}

// List mocks base method.
func (m *MockSeriesRepository) List(ctx context.Context, userId uuid.UUID, state models.StateType, limit, offset uint64) ([]models.Series, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userId, state, limit, offset)
	ret0, _ := ret[0].([]models.Series)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSeriesRepositoryMockRecorder) List(ctx, userId, state, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSeriesRepository)(nil).List), ctx, userId, state, limit, offset)
}

// Update mocks base method.
func (m *MockSeriesRepository) Update(ctx context.Context, params *models.Series) (*models.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*models.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSeriesRepositoryMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSeriesRepository)(nil).Update), ctx, params)
}

// UpdateByTmdbId mocks base method.
func (m *MockSeriesRepository) UpdateByTmdbId(ctx context.Context, params *models.Series) (*models.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTmdbId", ctx, params)
	ret0, _ := ret[0].(*models.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByTmdbId indicates an expected call of UpdateByTmdbId.
func (mr *MockSeriesRepositoryMockRecorder) UpdateByTmdbId(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTmdbId", reflect.TypeOf((*MockSeriesRepository)(nil).UpdateByTmdbId), ctx, params)
}
