// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repositories/sync.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/repositories/sync.go -destination=internal/app/repositories/sync_mock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncRepository is a mock of SyncRepository interface.
type MockSyncRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSyncRepositoryMockRecorder
	isgomock struct{}
}

// MockSyncRepositoryMockRecorder is the mock recorder for MockSyncRepository.
type MockSyncRepositoryMockRecorder struct {
	mock *MockSyncRepository
}

// NewMockSyncRepository creates a new mock instance.
func NewMockSyncRepository(ctrl *gomock.Controller) *MockSyncRepository {
	mock := &MockSyncRepository{ctrl: ctrl}
	mock.recorder = &MockSyncRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncRepository) EXPECT() *MockSyncRepositoryMockRecorder {
	return m.recorder
}

// FindMoviesToSync mocks base method.
func (m *MockSyncRepository) FindMoviesToSync(ctx context.Context, staleBefore, releaseCutoff time.Time, limit int) ([]models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMoviesToSync", ctx, staleBefore, releaseCutoff, limit)
	ret0, _ := ret[0].([]models.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMoviesToSync indicates an expected call of FindMoviesToSync.
func (mr *MockSyncRepositoryMockRecorder) FindMoviesToSync(ctx, staleBefore, releaseCutoff, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMoviesToSync", reflect.TypeOf((*MockSyncRepository)(nil).FindMoviesToSync), ctx, staleBefore, releaseCutoff, limit)
}

// FindSeriesToSync mocks base method.
func (m *MockSyncRepository) FindSeriesToSync(ctx context.Context, staleBefore, airCutoff time.Time, activeStatuses []string, limit int) ([]models.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSeriesToSync", ctx, staleBefore, airCutoff, activeStatuses, limit)
	ret0, _ := ret[0].([]models.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSeriesToSync indicates an expected call of FindSeriesToSync.
func (mr *MockSyncRepositoryMockRecorder) FindSeriesToSync(ctx, staleBefore, airCutoff, activeStatuses, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSeriesToSync", reflect.TypeOf((*MockSyncRepository)(nil).FindSeriesToSync), ctx, staleBefore, airCutoff, activeStatuses, limit)
}

// SyncMovie mocks base method.
func (m *MockSyncRepository) SyncMovie(ctx context.Context, id uuid.UUID, in models.MovieSyncInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncMovie", ctx, id, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncMovie indicates an expected call of SyncMovie.
func (mr *MockSyncRepositoryMockRecorder) SyncMovie(ctx, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncMovie", reflect.TypeOf((*MockSyncRepository)(nil).SyncMovie), ctx, id, in)
}

// SyncSeries mocks base method.
func (m *MockSyncRepository) SyncSeries(ctx context.Context, userId uuid.UUID, tmdbId uint64, in models.SeriesSyncInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncSeries", ctx, userId, tmdbId, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncSeries indicates an expected call of SyncSeries.
func (mr *MockSyncRepositoryMockRecorder) SyncSeries(ctx, userId, tmdbId, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncSeries", reflect.TypeOf((*MockSyncRepository)(nil).SyncSeries), ctx, userId, tmdbId, in)
}

// TouchMovieSynced mocks base method.
func (m *MockSyncRepository) TouchMovieSynced(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchMovieSynced", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchMovieSynced indicates an expected call of TouchMovieSynced.
func (mr *MockSyncRepositoryMockRecorder) TouchMovieSynced(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchMovieSynced", reflect.TypeOf((*MockSyncRepository)(nil).TouchMovieSynced), ctx, id)
}

// TouchSeriesSynced mocks base method.
func (m *MockSyncRepository) TouchSeriesSynced(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchSeriesSynced", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchSeriesSynced indicates an expected call of TouchSeriesSynced.
func (mr *MockSyncRepositoryMockRecorder) TouchSeriesSynced(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchSeriesSynced", reflect.TypeOf((*MockSyncRepository)(nil).TouchSeriesSynced), ctx, id)
}
