// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/catalog.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/catalog.go -destination=internal/app/controllers/catalog_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCatalogController is a mock of CatalogController interface.
type MockCatalogController struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogControllerMockRecorder
	isgomock struct{}
}

// MockCatalogControllerMockRecorder is the mock recorder for MockCatalogController.
type MockCatalogControllerMockRecorder struct {
	mock *MockCatalogController
}

// NewMockCatalogController creates a new mock instance.
func NewMockCatalogController(ctrl *gomock.Controller) *MockCatalogController {
	mock := &MockCatalogController{ctrl: ctrl}
	mock.recorder = &MockCatalogControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogController) EXPECT() *MockCatalogControllerMockRecorder {
	return m.recorder
}

// HandleSearchGames mocks base method.
func (m *MockCatalogController) HandleSearchGames(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSearchGames", w, r)
}

// HandleSearchGames indicates an expected call of HandleSearchGames.
func (mr *MockCatalogControllerMockRecorder) HandleSearchGames(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSearchGames", reflect.TypeOf((*MockCatalogController)(nil).HandleSearchGames), w, r)
}

// HandleSearchMovies mocks base method.
func (m *MockCatalogController) HandleSearchMovies(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSearchMovies", w, r)
}

// HandleSearchMovies indicates an expected call of HandleSearchMovies.
func (mr *MockCatalogControllerMockRecorder) HandleSearchMovies(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSearchMovies", reflect.TypeOf((*MockCatalogController)(nil).HandleSearchMovies), w, r)
}

// HandleSearchPeople mocks base method.
func (m *MockCatalogController) HandleSearchPeople(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSearchPeople", w, r)
}

// HandleSearchPeople indicates an expected call of HandleSearchPeople.
func (mr *MockCatalogControllerMockRecorder) HandleSearchPeople(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSearchPeople", reflect.TypeOf((*MockCatalogController)(nil).HandleSearchPeople), w, r)
}

// HandleSearchSeries mocks base method.
func (m *MockCatalogController) HandleSearchSeries(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSearchSeries", w, r)
}

// HandleSearchSeries indicates an expected call of HandleSearchSeries.
func (mr *MockCatalogControllerMockRecorder) HandleSearchSeries(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSearchSeries", reflect.TypeOf((*MockCatalogController)(nil).HandleSearchSeries), w, r)
}

// HandleTrendingGames mocks base method.
func (m *MockCatalogController) HandleTrendingGames(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleTrendingGames", w, r)
}

// HandleTrendingGames indicates an expected call of HandleTrendingGames.
func (mr *MockCatalogControllerMockRecorder) HandleTrendingGames(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTrendingGames", reflect.TypeOf((*MockCatalogController)(nil).HandleTrendingGames), w, r)
}

// HandleTrendingMovies mocks base method.
func (m *MockCatalogController) HandleTrendingMovies(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleTrendingMovies", w, r)
}

// HandleTrendingMovies indicates an expected call of HandleTrendingMovies.
func (mr *MockCatalogControllerMockRecorder) HandleTrendingMovies(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTrendingMovies", reflect.TypeOf((*MockCatalogController)(nil).HandleTrendingMovies), w, r)
}

// HandleTrendingPeople mocks base method.
func (m *MockCatalogController) HandleTrendingPeople(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleTrendingPeople", w, r)
}

// HandleTrendingPeople indicates an expected call of HandleTrendingPeople.
func (mr *MockCatalogControllerMockRecorder) HandleTrendingPeople(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTrendingPeople", reflect.TypeOf((*MockCatalogController)(nil).HandleTrendingPeople), w, r)
}

// HandleTrendingSeries mocks base method.
func (m *MockCatalogController) HandleTrendingSeries(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleTrendingSeries", w, r)
}

// HandleTrendingSeries indicates an expected call of HandleTrendingSeries.
func (mr *MockCatalogControllerMockRecorder) HandleTrendingSeries(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTrendingSeries", reflect.TypeOf((*MockCatalogController)(nil).HandleTrendingSeries), w, r)
}
