// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/games.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/games.go -destination=internal/app/controllers/games_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGamesController is a mock of GamesController interface.
type MockGamesController struct {
	ctrl     *gomock.Controller
	recorder *MockGamesControllerMockRecorder
	isgomock struct{}
}

// MockGamesControllerMockRecorder is the mock recorder for MockGamesController.
type MockGamesControllerMockRecorder struct {
	mock *MockGamesController
}

// NewMockGamesController creates a new mock instance.
func NewMockGamesController(ctrl *gomock.Controller) *MockGamesController {
	mock := &MockGamesController{ctrl: ctrl}
	mock.recorder = &MockGamesControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGamesController) EXPECT() *MockGamesControllerMockRecorder {
	return m.recorder
}

// HandleCreate mocks base method.
func (m *MockGamesController) HandleCreate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleCreate", w, r)
}

// HandleCreate indicates an expected call of HandleCreate.
func (mr *MockGamesControllerMockRecorder) HandleCreate(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCreate", reflect.TypeOf((*MockGamesController)(nil).HandleCreate), w, r)
}

// HandleDelete mocks base method.
func (m *MockGamesController) HandleDelete(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleDelete", w, r)
}

// HandleDelete indicates an expected call of HandleDelete.
func (mr *MockGamesControllerMockRecorder) HandleDelete(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDelete", reflect.TypeOf((*MockGamesController)(nil).HandleDelete), w, r)
}

// HandleDetails mocks base method.
func (m *MockGamesController) HandleDetails(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleDetails", w, r)
}

// HandleDetails indicates an expected call of HandleDetails.
func (mr *MockGamesControllerMockRecorder) HandleDetails(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDetails", reflect.TypeOf((*MockGamesController)(nil).HandleDetails), w, r)
}

// HandleList mocks base method.
func (m *MockGamesController) HandleList(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleList", w, r)
}

// HandleList indicates an expected call of HandleList.
func (mr *MockGamesControllerMockRecorder) HandleList(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleList", reflect.TypeOf((*MockGamesController)(nil).HandleList), w, r)
}

// HandleUpdate mocks base method.
func (m *MockGamesController) HandleUpdate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUpdate", w, r)
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockGamesControllerMockRecorder) HandleUpdate(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockGamesController)(nil).HandleUpdate), w, r)
}
