// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/integrations.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/integrations.go -destination=internal/app/controllers/integrations_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIntegrationsController is a mock of IntegrationsController interface.
type MockIntegrationsController struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationsControllerMockRecorder
	isgomock struct{}
}

// MockIntegrationsControllerMockRecorder is the mock recorder for MockIntegrationsController.
type MockIntegrationsControllerMockRecorder struct {
	mock *MockIntegrationsController
}

// NewMockIntegrationsController creates a new mock instance.
func NewMockIntegrationsController(ctrl *gomock.Controller) *MockIntegrationsController {
	mock := &MockIntegrationsController{ctrl: ctrl}
	mock.recorder = &MockIntegrationsControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegrationsController) EXPECT() *MockIntegrationsControllerMockRecorder {
	return m.recorder
}

// HandleCreateToken mocks base method.
func (m *MockIntegrationsController) HandleCreateToken(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleCreateToken", w, r)
}

// HandleCreateToken indicates an expected call of HandleCreateToken.
func (mr *MockIntegrationsControllerMockRecorder) HandleCreateToken(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCreateToken", reflect.TypeOf((*MockIntegrationsController)(nil).HandleCreateToken), w, r)
}

// HandleJellyfinWebhook mocks base method.
func (m *MockIntegrationsController) HandleJellyfinWebhook(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleJellyfinWebhook", w, r)
}

// HandleJellyfinWebhook indicates an expected call of HandleJellyfinWebhook.
func (mr *MockIntegrationsControllerMockRecorder) HandleJellyfinWebhook(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleJellyfinWebhook", reflect.TypeOf((*MockIntegrationsController)(nil).HandleJellyfinWebhook), w, r)
}

// HandleRevoke mocks base method.
func (m *MockIntegrationsController) HandleRevoke(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRevoke", w, r)
}

// HandleRevoke indicates an expected call of HandleRevoke.
func (mr *MockIntegrationsControllerMockRecorder) HandleRevoke(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRevoke", reflect.TypeOf((*MockIntegrationsController)(nil).HandleRevoke), w, r)
}
