// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/series.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/series.go -destination=internal/app/controllers/series_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSeriesController is a mock of SeriesController interface.
type MockSeriesController struct {
	ctrl     *gomock.Controller
	recorder *MockSeriesControllerMockRecorder
	isgomock struct{}
}

// MockSeriesControllerMockRecorder is the mock recorder for MockSeriesController.
type MockSeriesControllerMockRecorder struct {
	mock *MockSeriesController
}

// NewMockSeriesController creates a new mock instance.
func NewMockSeriesController(ctrl *gomock.Controller) *MockSeriesController {
	mock := &MockSeriesController{ctrl: ctrl}
	mock.recorder = &MockSeriesControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeriesController) EXPECT() *MockSeriesControllerMockRecorder {
	return m.recorder
}

// HandleCreate mocks base method.
func (m *MockSeriesController) HandleCreate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleCreate", w, r)
}

// HandleCreate indicates an expected call of HandleCreate.
func (mr *MockSeriesControllerMockRecorder) HandleCreate(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCreate", reflect.TypeOf((*MockSeriesController)(nil).HandleCreate), w, r)
}

// HandleDelete mocks base method.
func (m *MockSeriesController) HandleDelete(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleDelete", w, r)
}

// HandleDelete indicates an expected call of HandleDelete.
func (mr *MockSeriesControllerMockRecorder) HandleDelete(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDelete", reflect.TypeOf((*MockSeriesController)(nil).HandleDelete), w, r)
}

// HandleDetails mocks base method.
func (m *MockSeriesController) HandleDetails(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleDetails", w, r)
}

// HandleDetails indicates an expected call of HandleDetails.
func (mr *MockSeriesControllerMockRecorder) HandleDetails(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDetails", reflect.TypeOf((*MockSeriesController)(nil).HandleDetails), w, r)
}

// HandleList mocks base method.
func (m *MockSeriesController) HandleList(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleList", w, r)
}

// HandleList indicates an expected call of HandleList.
func (mr *MockSeriesControllerMockRecorder) HandleList(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleList", reflect.TypeOf((*MockSeriesController)(nil).HandleList), w, r)
}

// HandleMarkEpisodeWatched mocks base method.
func (m *MockSeriesController) HandleMarkEpisodeWatched(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleMarkEpisodeWatched", w, r)
}

// HandleMarkEpisodeWatched indicates an expected call of HandleMarkEpisodeWatched.
func (mr *MockSeriesControllerMockRecorder) HandleMarkEpisodeWatched(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMarkEpisodeWatched", reflect.TypeOf((*MockSeriesController)(nil).HandleMarkEpisodeWatched), w, r)
}

// HandleMarkSeasonWatched mocks base method.
func (m *MockSeriesController) HandleMarkSeasonWatched(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleMarkSeasonWatched", w, r)
}

// HandleMarkSeasonWatched indicates an expected call of HandleMarkSeasonWatched.
func (mr *MockSeriesControllerMockRecorder) HandleMarkSeasonWatched(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMarkSeasonWatched", reflect.TypeOf((*MockSeriesController)(nil).HandleMarkSeasonWatched), w, r)
}

// HandleMarkShowWatched mocks base method.
func (m *MockSeriesController) HandleMarkShowWatched(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleMarkShowWatched", w, r)
}

// HandleMarkShowWatched indicates an expected call of HandleMarkShowWatched.
func (mr *MockSeriesControllerMockRecorder) HandleMarkShowWatched(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMarkShowWatched", reflect.TypeOf((*MockSeriesController)(nil).HandleMarkShowWatched), w, r)
}

// HandleProgress mocks base method.
func (m *MockSeriesController) HandleProgress(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleProgress", w, r)
}

// HandleProgress indicates an expected call of HandleProgress.
func (mr *MockSeriesControllerMockRecorder) HandleProgress(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleProgress", reflect.TypeOf((*MockSeriesController)(nil).HandleProgress), w, r)
}

// HandleUnmarkEpisodeWatched mocks base method.
func (m *MockSeriesController) HandleUnmarkEpisodeWatched(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUnmarkEpisodeWatched", w, r)
}

// HandleUnmarkEpisodeWatched indicates an expected call of HandleUnmarkEpisodeWatched.
func (mr *MockSeriesControllerMockRecorder) HandleUnmarkEpisodeWatched(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUnmarkEpisodeWatched", reflect.TypeOf((*MockSeriesController)(nil).HandleUnmarkEpisodeWatched), w, r)
}

// HandleUnmarkSeasonWatched mocks base method.
func (m *MockSeriesController) HandleUnmarkSeasonWatched(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUnmarkSeasonWatched", w, r)
}

// HandleUnmarkSeasonWatched indicates an expected call of HandleUnmarkSeasonWatched.
func (mr *MockSeriesControllerMockRecorder) HandleUnmarkSeasonWatched(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUnmarkSeasonWatched", reflect.TypeOf((*MockSeriesController)(nil).HandleUnmarkSeasonWatched), w, r)
}

// HandleUnmarkShowWatched mocks base method.
func (m *MockSeriesController) HandleUnmarkShowWatched(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUnmarkShowWatched", w, r)
}

// HandleUnmarkShowWatched indicates an expected call of HandleUnmarkShowWatched.
func (mr *MockSeriesControllerMockRecorder) HandleUnmarkShowWatched(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUnmarkShowWatched", reflect.TypeOf((*MockSeriesController)(nil).HandleUnmarkShowWatched), w, r)
}

// HandleUpdate mocks base method.
func (m *MockSeriesController) HandleUpdate(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUpdate", w, r)
}

// HandleUpdate indicates an expected call of HandleUpdate.
func (mr *MockSeriesControllerMockRecorder) HandleUpdate(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpdate", reflect.TypeOf((*MockSeriesController)(nil).HandleUpdate), w, r)
}
