// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/controllers/upnext.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/controllers/upnext.go -destination=internal/app/controllers/upnext_mock.go -package=controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpNextController is a mock of UpNextController interface.
type MockUpNextController struct {
	ctrl     *gomock.Controller
	recorder *MockUpNextControllerMockRecorder
	isgomock struct{}
}

// MockUpNextControllerMockRecorder is the mock recorder for MockUpNextController.
type MockUpNextControllerMockRecorder struct {
	mock *MockUpNextController
}

// NewMockUpNextController creates a new mock instance.
func NewMockUpNextController(ctrl *gomock.Controller) *MockUpNextController {
	mock := &MockUpNextController{ctrl: ctrl}
	mock.recorder = &MockUpNextControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpNextController) EXPECT() *MockUpNextControllerMockRecorder {
	return m.recorder
}

// HandleUpNext mocks base method.
func (m *MockUpNextController) HandleUpNext(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUpNext", w, r)
}

// HandleUpNext indicates an expected call of HandleUpNext.
func (mr *MockUpNextControllerMockRecorder) HandleUpNext(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUpNext", reflect.TypeOf((*MockUpNextController)(nil).HandleUpNext), w, r)
}
