// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEpisodeBySeasonAndTmdbId = `-- name: DeleteEpisodeBySeasonAndTmdbId :exec
DELETE FROM episodes WHERE season_id = $1 AND tmdb_id = $2
`

type DeleteEpisodeBySeasonAndTmdbIdParams struct {
	SeasonID uuid.UUID
	TmdbID   uint64
}

func (q *Queries) DeleteEpisodeBySeasonAndTmdbId(ctx context.Context, arg DeleteEpisodeBySeasonAndTmdbIdParams) error {
	_, err := q.db.Exec(ctx, deleteEpisodeBySeasonAndTmdbId, arg.SeasonID, arg.TmdbID)
	return err
}

const upsertEpisode = `-- name: UpsertEpisode :one
INSERT INTO episodes (
  season_id,
  tmdb_id,
  title,
  poster_path,
  runtime,
  state,
  air_at,
  watched_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, CASE WHEN $6 = 'watched'::state_types THEN NOW() ELSE NULL END
)
ON CONFLICT (season_id, tmdb_id) DO UPDATE SET
  title = EXCLUDED.title,
  poster_path = EXCLUDED.poster_path,
  runtime = EXCLUDED.runtime,
  state = EXCLUDED.state,
  air_at = EXCLUDED.air_at,
  watched_at = CASE WHEN EXCLUDED.state = 'watched'::state_types THEN COALESCE(episodes.watched_at, NOW()) ELSE NULL END,
  updated_at = NOW()
RETURNING
  id,
  season_id,
  tmdb_id,
  title,
  poster_path,
  runtime,
  state,
  air_at,
  watched_at,
  created_at,
  updated_at
`

type UpsertEpisodeParams struct {
	SeasonID   uuid.UUID
	TmdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	State      StateTypes
	AirAt      pgtype.Timestamp
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, upsertEpisode,
		arg.SeasonID,
		arg.TmdbID,
		arg.Title,
		arg.PosterPath,
		arg.Runtime,
		arg.State,
		arg.AirAt,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.State,
		&i.AirAt,
		&i.WatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
