// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEpisodesBySeasonId = `-- name: CountEpisodesBySeasonId :one
SELECT COUNT(*)
FROM episodes e
  JOIN seasons s ON e.season_id = s.id
  JOIN series t ON s.series_id = t.id
WHERE e.season_id = $1 AND t.user_id = $2
`

type CountEpisodesBySeasonIdParams struct {
	SeasonID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) CountEpisodesBySeasonId(ctx context.Context, arg CountEpisodesBySeasonIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEpisodesBySeasonId, arg.SeasonID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWatchedEpisodesBySeasonId = `-- name: CountWatchedEpisodesBySeasonId :one
SELECT COUNT(*)
FROM episodes e
  JOIN seasons s ON e.season_id = s.id
  JOIN series t ON s.series_id = t.id
WHERE e.season_id = $1 AND t.user_id = $2 AND e.state = $3
`

type CountWatchedEpisodesBySeasonIdParams struct {
	SeasonID uuid.UUID
	UserID   uuid.UUID
	State    StateTypes
}

func (q *Queries) CountWatchedEpisodesBySeasonId(ctx context.Context, arg CountWatchedEpisodesBySeasonIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWatchedEpisodesBySeasonId, arg.SeasonID, arg.UserID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (
  season_id,
  tmdb_id,
  title,
  poster_path,
  runtime,
  state,
  air_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING
  id,
  season_id,
  tmdb_id,
  title,
  poster_path,
  runtime,
  state,
  air_at,
  created_at,
  updated_at
`

type CreateEpisodeParams struct {
	SeasonID   uuid.UUID
	TmdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	State      StateTypes
	AirAt      pgtype.Timestamp
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.SeasonID,
		arg.TmdbID,
		arg.Title,
		arg.PosterPath,
		arg.Runtime,
		arg.State,
		arg.AirAt,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.State,
		&i.AirAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEpisode = `-- name: DeleteEpisode :exec
DELETE FROM episodes WHERE id = $1
`

func (q *Queries) DeleteEpisode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEpisode, id)
	return err
}

const deleteEpisodeBySeasonAndTmdbId = `-- name: DeleteEpisodeBySeasonAndTmdbId :exec
DELETE FROM episodes WHERE season_id = $1 AND tmdb_id = $2
`

type DeleteEpisodeBySeasonAndTmdbIdParams struct {
	SeasonID uuid.UUID
	TmdbID   uint64
}

func (q *Queries) DeleteEpisodeBySeasonAndTmdbId(ctx context.Context, arg DeleteEpisodeBySeasonAndTmdbIdParams) error {
	_, err := q.db.Exec(ctx, deleteEpisodeBySeasonAndTmdbId, arg.SeasonID, arg.TmdbID)
	return err
}

const findEpisodeById = `-- name: FindEpisodeById :one
SELECT
  e.id,
  e.season_id,
  e.tmdb_id,
  e.title,
  e.poster_path,
  e.runtime,
  e.state,
  e.air_at,
  e.created_at,
  e.updated_at
FROM episodes e
  JOIN seasons s ON e.season_id = s.id
  JOIN series t ON s.series_id = t.id
WHERE e.id = $1 AND t.user_id = $2
`

type FindEpisodeByIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) FindEpisodeById(ctx context.Context, arg FindEpisodeByIdParams) (Episode, error) {
	row := q.db.QueryRow(ctx, findEpisodeById, arg.ID, arg.UserID)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.State,
		&i.AirAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEpisodesBySeasonId = `-- name: FindEpisodesBySeasonId :many
SELECT
  e.id,
  e.season_id,
  e.tmdb_id,
  e.title,
  e.poster_path,
  e.runtime,
  e.state,
  e.air_at,
  e.created_at,
  e.updated_at
FROM episodes e
  JOIN seasons s ON e.season_id = s.id
  JOIN series t ON s.series_id = t.id
WHERE e.season_id = $1 AND t.user_id = $2
ORDER BY e.air_at DESC
`

type FindEpisodesBySeasonIdParams struct {
	SeasonID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) FindEpisodesBySeasonId(ctx context.Context, arg FindEpisodesBySeasonIdParams) ([]Episode, error) {
	rows, err := q.db.Query(ctx, findEpisodesBySeasonId, arg.SeasonID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.TmdbID,
			&i.Title,
			&i.PosterPath,
			&i.Runtime,
			&i.State,
			&i.AirAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpisode = `-- name: UpdateEpisode :one
UPDATE episodes
SET
  title = $3,
  poster_path = $4,
  runtime = $5,
  air_at = $6,
  state = $7,
  updated_at = NOW()
WHERE episodes.id = $1
  AND EXISTS (
  SELECT 1 FROM seasons s
    JOIN series t ON s.series_id = t.id
  WHERE episodes.season_id = s.id AND t.user_id = $2
)
RETURNING
  id,
  season_id,
  tmdb_id,
  title,
  poster_path,
  runtime,
  state,
  air_at,
  created_at,
  updated_at
`

type UpdateEpisodeParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Title      string
	PosterPath string
	Runtime    uint64
	AirAt      pgtype.Timestamp
	State      StateTypes
}

func (q *Queries) UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, updateEpisode,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.PosterPath,
		arg.Runtime,
		arg.AirAt,
		arg.State,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.State,
		&i.AirAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEpisodeByTmdbId = `-- name: UpdateEpisodeByTmdbId :one
UPDATE episodes
SET
  state = $3,
  updated_at = NOW()
WHERE episodes.tmdb_id = $1
  AND EXISTS (
  SELECT 1 FROM seasons s
    JOIN series t ON s.series_id = t.id
  WHERE episodes.season_id = s.id AND t.user_id = $2
)
  RETURNING
  id,
  season_id,
  tmdb_id,
  title,
  poster_path,
  runtime,
  state,
  air_at,
  created_at,
  updated_at
`

type UpdateEpisodeByTmdbIdParams struct {
	TmdbID uint64
	UserID uuid.UUID
	State  StateTypes
}

func (q *Queries) UpdateEpisodeByTmdbId(ctx context.Context, arg UpdateEpisodeByTmdbIdParams) (Episode, error) {
	row := q.db.QueryRow(ctx, updateEpisodeByTmdbId, arg.TmdbID, arg.UserID, arg.State)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.State,
		&i.AirAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEpisode = `-- name: UpsertEpisode :one
INSERT INTO episodes (
  season_id,
  tmdb_id,
  title,
  poster_path,
  runtime,
  state,
  air_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (season_id, tmdb_id) DO UPDATE SET
  title = EXCLUDED.title,
  poster_path = EXCLUDED.poster_path,
  runtime = EXCLUDED.runtime,
  state = EXCLUDED.state,
  air_at = EXCLUDED.air_at,
  updated_at = NOW()
RETURNING
  id,
  season_id,
  tmdb_id,
  title,
  poster_path,
  runtime,
  state,
  air_at,
  created_at,
  updated_at
`

type UpsertEpisodeParams struct {
	SeasonID   uuid.UUID
	TmdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	State      StateTypes
	AirAt      pgtype.Timestamp
}

func (q *Queries) UpsertEpisode(ctx context.Context, arg UpsertEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, upsertEpisode,
		arg.SeasonID,
		arg.TmdbID,
		arg.Title,
		arg.PosterPath,
		arg.Runtime,
		arg.State,
		arg.AirAt,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.State,
		&i.AirAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
