// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (
  user_id,
  igdb_id,
  title,
  poster_path,
  runtime,
  state,
  played_at
) VALUES (
  $1, $2, $3, $4, $5, $6, CASE WHEN $6 = 'played'::state_types THEN NOW() ELSE NULL END
)
RETURNING
  id,
  user_id,
  igdb_id,
  title,
  poster_path,
  runtime,
  state,
  pinned,
  created_at,
  updated_at,
  played_at
`

type CreateGameParams struct {
	UserID     uuid.UUID
	IgdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	State      StateTypes
}

type CreateGameRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	IgdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	State      StateTypes
	Pinned     bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	PlayedAt   pgtype.Timestamptz
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (CreateGameRow, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.UserID,
		arg.IgdbID,
		arg.Title,
		arg.PosterPath,
		arg.Runtime,
		arg.State,
	)
	var i CreateGameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IgdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayedAt,
	)
	return i, err
}

const deleteGameByIgdbId = `-- name: DeleteGameByIgdbId :exec
DELETE FROM games WHERE igdb_id = $1 AND user_id = $2
`

type DeleteGameByIgdbIdParams struct {
	IgdbID uint64
	UserID uuid.UUID
}

func (q *Queries) DeleteGameByIgdbId(ctx context.Context, arg DeleteGameByIgdbIdParams) error {
	_, err := q.db.Exec(ctx, deleteGameByIgdbId, arg.IgdbID, arg.UserID)
	return err
}

const findGameByIgdbId = `-- name: FindGameByIgdbId :one
SELECT
  id,
  user_id,
  igdb_id,
  title,
  poster_path,
  runtime,
  pinned,
  state,
  played_at,
  created_at,
  updated_at
FROM games
WHERE igdb_id = $1 AND user_id = $2 LIMIT 1
`

type FindGameByIgdbIdParams struct {
	IgdbID uint64
	UserID uuid.UUID
}

type FindGameByIgdbIdRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	IgdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	Pinned     bool
	State      StateTypes
	PlayedAt   pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) FindGameByIgdbId(ctx context.Context, arg FindGameByIgdbIdParams) (FindGameByIgdbIdRow, error) {
	row := q.db.QueryRow(ctx, findGameByIgdbId, arg.IgdbID, arg.UserID)
	var i FindGameByIgdbIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IgdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.Pinned,
		&i.State,
		&i.PlayedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findGamesByIgdbIds = `-- name: FindGamesByIgdbIds :many
SELECT
  id,
  user_id,
  igdb_id,
  title,
  poster_path,
  runtime,
  pinned,
  state,
  played_at,
  created_at,
  updated_at
FROM games
WHERE igdb_id = ANY($1::integer[]) AND user_id = $2
`

type FindGamesByIgdbIdsParams struct {
	IgdbIds []int32
	UserID  uuid.UUID
}

type FindGamesByIgdbIdsRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	IgdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	Pinned     bool
	State      StateTypes
	PlayedAt   pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) FindGamesByIgdbIds(ctx context.Context, arg FindGamesByIgdbIdsParams) ([]FindGamesByIgdbIdsRow, error) {
	rows, err := q.db.Query(ctx, findGamesByIgdbIds, arg.IgdbIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGamesByIgdbIdsRow
	for rows.Next() {
		var i FindGamesByIgdbIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IgdbID,
			&i.Title,
			&i.PosterPath,
			&i.Runtime,
			&i.Pinned,
			&i.State,
			&i.PlayedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGamesByState = `-- name: FindGamesByState :many
WITH counter AS (
  SELECT COUNT(*) AS total
  FROM games
  WHERE user_id = $1 AND state = $2
)
SELECT
  g.id,
  g.user_id,
  g.igdb_id,
  g.title,
  g.poster_path,
  g.runtime,
  g.pinned,
  g.state,
  g.played_at,
  g.created_at,
  g.updated_at,
  counter.total
FROM games g CROSS JOIN counter
WHERE g.user_id = $1 AND g.state = $2
ORDER BY g.pinned DESC, g.created_at DESC LIMIT $3 OFFSET $4
`

type FindGamesByStateParams struct {
	UserID uuid.UUID
	State  StateTypes
	Limit  int32
	Offset int32
}

type FindGamesByStateRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	IgdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	Pinned     bool
	State      StateTypes
	PlayedAt   pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Total      int64
}

func (q *Queries) FindGamesByState(ctx context.Context, arg FindGamesByStateParams) ([]FindGamesByStateRow, error) {
	rows, err := q.db.Query(ctx, findGamesByState,
		arg.UserID,
		arg.State,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindGamesByStateRow
	for rows.Next() {
		var i FindGamesByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IgdbID,
			&i.Title,
			&i.PosterPath,
			&i.Runtime,
			&i.Pinned,
			&i.State,
			&i.PlayedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET
  title = $2,
  poster_path = $3,
  runtime = $4,
  updated_at = NOW()
WHERE id = $1
RETURNING
  id,
  user_id,
  igdb_id,
  title,
  poster_path,
  runtime,
  state,
  pinned,
  created_at,
  updated_at,
  played_at
`

type UpdateGameParams struct {
	ID         uuid.UUID
	Title      string
	PosterPath string
	Runtime    uint64
}

type UpdateGameRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	IgdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	State      StateTypes
	Pinned     bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	PlayedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (UpdateGameRow, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.ID,
		arg.Title,
		arg.PosterPath,
		arg.Runtime,
	)
	var i UpdateGameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IgdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayedAt,
	)
	return i, err
}

const updateGameByIgdbId = `-- name: UpdateGameByIgdbId :one
UPDATE games
SET
  state = $3,
  pinned = $4,
  played_at = CASE WHEN $3 = 'played'::state_types THEN COALESCE(played_at, NOW()) ELSE NULL END,
  updated_at = NOW()
WHERE igdb_id = $1 AND user_id = $2
RETURNING
  id,
  user_id,
  igdb_id,
  title,
  poster_path,
  runtime,
  state,
  pinned,
  created_at,
  updated_at,
  played_at
`

type UpdateGameByIgdbIdParams struct {
	IgdbID uint64
	UserID uuid.UUID
	State  StateTypes
	Pinned bool
}

type UpdateGameByIgdbIdRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	IgdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	State      StateTypes
	Pinned     bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	PlayedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateGameByIgdbId(ctx context.Context, arg UpdateGameByIgdbIdParams) (UpdateGameByIgdbIdRow, error) {
	row := q.db.QueryRow(ctx, updateGameByIgdbId,
		arg.IgdbID,
		arg.UserID,
		arg.State,
		arg.Pinned,
	)
	var i UpdateGameByIgdbIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IgdbID,
		&i.Title,
		&i.PosterPath,
		&i.Runtime,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlayedAt,
	)
	return i, err
}
