// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integrations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations WHERE user_id = $1 AND provider = $2
`

type DeleteIntegrationParams struct {
	UserID   uuid.UUID
	Provider ProviderType
}

func (q *Queries) DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) error {
	_, err := q.db.Exec(ctx, deleteIntegration, arg.UserID, arg.Provider)
	return err
}

const findIntegrationByTokenHash = `-- name: FindIntegrationByTokenHash :one
SELECT
  i.id,
  i.user_id,
  i.provider,
  i.token_hash,
  i.created_at,
  i.updated_at
FROM integrations i
  JOIN users u ON u.id = i.user_id
WHERE i.token_hash = $1 AND i.provider = $2 AND u.deleted_at IS NULL LIMIT 1
`

type FindIntegrationByTokenHashParams struct {
	TokenHash string
	Provider  ProviderType
}

func (q *Queries) FindIntegrationByTokenHash(ctx context.Context, arg FindIntegrationByTokenHashParams) (Integration, error) {
	row := q.db.QueryRow(ctx, findIntegrationByTokenHash, arg.TokenHash, arg.Provider)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIntegration = `-- name: UpsertIntegration :one
INSERT INTO integrations (
  user_id,
  provider,
  token_hash
) VALUES (
  $1, $2, $3
)
ON CONFLICT (user_id, provider) DO UPDATE SET
  token_hash = EXCLUDED.token_hash,
  updated_at = NOW()
RETURNING
  id,
  user_id,
  provider,
  token_hash,
  created_at,
  updated_at
`

type UpsertIntegrationParams struct {
	UserID    uuid.UUID
	Provider  ProviderType
	TokenHash string
}

func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, upsertIntegration, arg.UserID, arg.Provider, arg.TokenHash)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
