// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AppearanceType string

const (
	AppearanceTypeSystem AppearanceType = "system"
	AppearanceTypeLight  AppearanceType = "light"
	AppearanceTypeDark   AppearanceType = "dark"
)

func (e *AppearanceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppearanceType(s)
	case string:
		*e = AppearanceType(s)
	default:
		return fmt.Errorf("unsupported scan type for AppearanceType: %T", src)
	}
	return nil
}

type NullAppearanceType struct {
	AppearanceType AppearanceType
	Valid          bool // Valid is true if AppearanceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppearanceType) Scan(value interface{}) error {
	if value == nil {
		ns.AppearanceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppearanceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppearanceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppearanceType), nil
}

type StateTypes string

const (
	StateTypesWant     StateTypes = "want"
	StateTypesWatching StateTypes = "watching"
	StateTypesWatched  StateTypes = "watched"
	StateTypesNone     StateTypes = "none"
)

func (e *StateTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StateTypes(s)
	case string:
		*e = StateTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for StateTypes: %T", src)
	}
	return nil
}

type NullStateTypes struct {
	StateTypes StateTypes
	Valid      bool // Valid is true if StateTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStateTypes) Scan(value interface{}) error {
	if value == nil {
		ns.StateTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StateTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStateTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StateTypes), nil
}

type Episode struct {
	ID         uuid.UUID
	SeasonID   uuid.UUID
	TmdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	State      StateTypes
	AirAt      pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	WatchedAt  pgtype.Timestamptz
}

type Movie struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TmdbID     uint64
	Title      string
	PosterPath string
	Runtime    uint64
	State      StateTypes
	Pinned     bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	WatchedAt  pgtype.Timestamptz
	SyncedAt   pgtype.Timestamptz
	ReleasedAt pgtype.Timestamptz
}

type Season struct {
	ID            uuid.UUID
	SeriesID      uuid.UUID
	TmdbID        uint64
	Title         string
	Number        uint64
	EpisodesCount uint64
	State         StateTypes
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	WatchedAt     pgtype.Timestamptz
}

type Series struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	TmdbID        uint64
	Title         string
	PosterPath    string
	SeasonsCount  uint64
	EpisodesCount uint64
	Status        string
	// the show's effective state, derived from watched seasons when the user has not chosen one
	State     StateTypes
	Pinned    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	// the state the user explicitly chose; NULL when the row was created by marking an episode
	TrackedState NullStateTypes
	SyncedAt     pgtype.Timestamptz
	LastAirAt    pgtype.Timestamptz
}

type User struct {
	ID                uuid.UUID
	Login             string
	Email             string
	EncryptedPassword string
	FirstName         string
	LastName          string
	Appearance        AppearanceType
	DeletedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
