// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countEpisodesBySeason = `-- name: CountEpisodesBySeason :one
SELECT COUNT(*) FROM episodes WHERE season_id = $1
`

func (q *Queries) CountEpisodesBySeason(ctx context.Context, seasonID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEpisodesBySeason, seasonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWatchedSeasonsBySeriesId = `-- name: CountWatchedSeasonsBySeriesId :one
SELECT COUNT(*)
FROM seasons s
  JOIN series t ON s.series_id = t.id
WHERE s.series_id = $1 AND t.user_id = $2 AND s.state = $3
`

type CountWatchedSeasonsBySeriesIdParams struct {
	SeriesID uuid.UUID
	UserID   uuid.UUID
	State    StateTypes
}

func (q *Queries) CountWatchedSeasonsBySeriesId(ctx context.Context, arg CountWatchedSeasonsBySeriesIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWatchedSeasonsBySeriesId, arg.SeriesID, arg.UserID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING
  id,
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state,
  created_at,
  updated_at
`

type CreateSeasonParams struct {
	SeriesID      uuid.UUID
	TmdbID        uint64
	Title         string
	Number        uint64
	EpisodesCount uint64
	State         StateTypes
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.SeriesID,
		arg.TmdbID,
		arg.Title,
		arg.Number,
		arg.EpisodesCount,
		arg.State,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.TmdbID,
		&i.Title,
		&i.Number,
		&i.EpisodesCount,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeason = `-- name: DeleteSeason :exec
DELETE FROM seasons WHERE id = $1
`

func (q *Queries) DeleteSeason(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeason, id)
	return err
}

const findSeasonById = `-- name: FindSeasonById :one
SELECT
  s.id,
  s.series_id,
  s.tmdb_id,
  s.title,
  s.number,
  s.episodes_count,
  s.state,
  s.created_at,
  s.updated_at
FROM seasons s
  JOIN series t ON s.series_id = t.id
WHERE s.id = $1
`

func (q *Queries) FindSeasonById(ctx context.Context, id uuid.UUID) (Season, error) {
	row := q.db.QueryRow(ctx, findSeasonById, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.TmdbID,
		&i.Title,
		&i.Number,
		&i.EpisodesCount,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSeasonBySeriesAndTmdbId = `-- name: FindSeasonBySeriesAndTmdbId :one
SELECT
  id,
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state,
  created_at,
  updated_at
FROM seasons
WHERE series_id = $1 AND tmdb_id = $2 LIMIT 1
`

type FindSeasonBySeriesAndTmdbIdParams struct {
	SeriesID uuid.UUID
	TmdbID   uint64
}

func (q *Queries) FindSeasonBySeriesAndTmdbId(ctx context.Context, arg FindSeasonBySeriesAndTmdbIdParams) (Season, error) {
	row := q.db.QueryRow(ctx, findSeasonBySeriesAndTmdbId, arg.SeriesID, arg.TmdbID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.TmdbID,
		&i.Title,
		&i.Number,
		&i.EpisodesCount,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSeasonsBySeriesId = `-- name: FindSeasonsBySeriesId :many
SELECT
  s.id,
  s.series_id,
  s.tmdb_id,
  s.title,
  s.number,
  s.episodes_count,
  s.state,
  s.created_at,
  s.updated_at
FROM seasons s
  JOIN series t ON s.series_id = t.id
WHERE s.series_id = $1 AND t.user_id = $2
ORDER BY s.number ASC
`

type FindSeasonsBySeriesIdParams struct {
	SeriesID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) FindSeasonsBySeriesId(ctx context.Context, arg FindSeasonsBySeriesIdParams) ([]Season, error) {
	rows, err := q.db.Query(ctx, findSeasonsBySeriesId, arg.SeriesID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.TmdbID,
			&i.Title,
			&i.Number,
			&i.EpisodesCount,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSeasonState = `-- name: SetSeasonState :exec
UPDATE seasons SET state = $2, updated_at = NOW() WHERE id = $1
`

type SetSeasonStateParams struct {
	ID    uuid.UUID
	State StateTypes
}

func (q *Queries) SetSeasonState(ctx context.Context, arg SetSeasonStateParams) error {
	_, err := q.db.Exec(ctx, setSeasonState, arg.ID, arg.State)
	return err
}

const updateSeason = `-- name: UpdateSeason :one
UPDATE seasons
SET
  title = $3,
  number = $4,
  episodes_count = $5,
  updated_at = NOW()
WHERE seasons.id = $1 AND EXISTS (
  SELECT 1 FROM series t
  WHERE seasons.series_id = t.id AND t.user_id = $2
)
RETURNING
  id,
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state,
  created_at,
  updated_at
`

type UpdateSeasonParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Title         string
	Number        uint64
	EpisodesCount uint64
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, updateSeason,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Number,
		arg.EpisodesCount,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.TmdbID,
		&i.Title,
		&i.Number,
		&i.EpisodesCount,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSeasonByTmdbId = `-- name: UpdateSeasonByTmdbId :one
UPDATE seasons
SET
  state = $3,
  updated_at = NOW()
WHERE seasons.tmdb_id = $1 AND EXISTS (
  SELECT 1 FROM series t
  WHERE seasons.series_id = t.id AND t.user_id = $2
)
  RETURNING
  id,
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state,
  created_at,
  updated_at
`

type UpdateSeasonByTmdbIdParams struct {
	TmdbID uint64
	UserID uuid.UUID
	State  StateTypes
}

func (q *Queries) UpdateSeasonByTmdbId(ctx context.Context, arg UpdateSeasonByTmdbIdParams) (Season, error) {
	row := q.db.QueryRow(ctx, updateSeasonByTmdbId, arg.TmdbID, arg.UserID, arg.State)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.TmdbID,
		&i.Title,
		&i.Number,
		&i.EpisodesCount,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSeason = `-- name: UpsertSeason :one
INSERT INTO seasons (
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (series_id, tmdb_id) DO UPDATE SET
  title = EXCLUDED.title,
  number = EXCLUDED.number,
  episodes_count = EXCLUDED.episodes_count,
  updated_at = NOW()
RETURNING
  id,
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state,
  created_at,
  updated_at
`

type UpsertSeasonParams struct {
	SeriesID      uuid.UUID
	TmdbID        uint64
	Title         string
	Number        uint64
	EpisodesCount uint64
	State         StateTypes
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, upsertSeason,
		arg.SeriesID,
		arg.TmdbID,
		arg.Title,
		arg.Number,
		arg.EpisodesCount,
		arg.State,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.TmdbID,
		&i.Title,
		&i.Number,
		&i.EpisodesCount,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
