// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countEpisodesBySeason = `-- name: CountEpisodesBySeason :one
SELECT COUNT(*) FROM episodes WHERE season_id = $1
`

func (q *Queries) CountEpisodesBySeason(ctx context.Context, seasonID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEpisodesBySeason, seasonID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSeason = `-- name: DeleteSeason :exec
DELETE FROM seasons WHERE id = $1
`

func (q *Queries) DeleteSeason(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeason, id)
	return err
}

const findSeasonBySeriesAndTmdbId = `-- name: FindSeasonBySeriesAndTmdbId :one
SELECT
  id,
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state,
  created_at,
  updated_at
FROM seasons
WHERE series_id = $1 AND tmdb_id = $2 LIMIT 1
`

type FindSeasonBySeriesAndTmdbIdParams struct {
	SeriesID uuid.UUID
	TmdbID   uint64
}

func (q *Queries) FindSeasonBySeriesAndTmdbId(ctx context.Context, arg FindSeasonBySeriesAndTmdbIdParams) (Season, error) {
	row := q.db.QueryRow(ctx, findSeasonBySeriesAndTmdbId, arg.SeriesID, arg.TmdbID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.TmdbID,
		&i.Title,
		&i.Number,
		&i.EpisodesCount,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSeasonState = `-- name: SetSeasonState :exec
UPDATE seasons SET state = $2, updated_at = NOW() WHERE id = $1
`

type SetSeasonStateParams struct {
	ID    uuid.UUID
	State StateTypes
}

func (q *Queries) SetSeasonState(ctx context.Context, arg SetSeasonStateParams) error {
	_, err := q.db.Exec(ctx, setSeasonState, arg.ID, arg.State)
	return err
}

const upsertSeason = `-- name: UpsertSeason :one
INSERT INTO seasons (
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (series_id, tmdb_id) DO UPDATE SET
  title = EXCLUDED.title,
  number = EXCLUDED.number,
  episodes_count = EXCLUDED.episodes_count,
  updated_at = NOW()
RETURNING
  id,
  series_id,
  tmdb_id,
  title,
  number,
  episodes_count,
  state,
  created_at,
  updated_at
`

type UpsertSeasonParams struct {
	SeriesID      uuid.UUID
	TmdbID        uint64
	Title         string
	Number        uint64
	EpisodesCount uint64
	State         StateTypes
}

func (q *Queries) UpsertSeason(ctx context.Context, arg UpsertSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, upsertSeason,
		arg.SeriesID,
		arg.TmdbID,
		arg.Title,
		arg.Number,
		arg.EpisodesCount,
		arg.State,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.TmdbID,
		&i.Title,
		&i.Number,
		&i.EpisodesCount,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
