// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: series.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEpisodesBySeriesId = `-- name: CountEpisodesBySeriesId :one
SELECT COUNT(*)
FROM episodes e
  JOIN seasons s ON e.season_id = s.id
WHERE s.series_id = $1
`

func (q *Queries) CountEpisodesBySeriesId(ctx context.Context, seriesID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEpisodesBySeriesId, seriesID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWatchedSeasonsBySeriesId = `-- name: CountWatchedSeasonsBySeriesId :one
SELECT COUNT(*)
FROM seasons
WHERE series_id = $1 AND state = 'watched' AND number > 0
`

func (q *Queries) CountWatchedSeasonsBySeriesId(ctx context.Context, seriesID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWatchedSeasonsBySeriesId, seriesID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  tracked_state
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $8
)
RETURNING
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  pinned,
  created_at,
  updated_at,
  tracked_state,
  synced_at,
  last_air_at
`

type CreateSeriesParams struct {
	UserID        uuid.UUID
	TmdbID        uint64
	Title         string
	PosterPath    string
	SeasonsCount  uint64
	EpisodesCount uint64
	Status        string
	State         StateTypes
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, createSeries,
		arg.UserID,
		arg.TmdbID,
		arg.Title,
		arg.PosterPath,
		arg.SeasonsCount,
		arg.EpisodesCount,
		arg.Status,
		arg.State,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.SeasonsCount,
		&i.EpisodesCount,
		&i.Status,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackedState,
		&i.SyncedAt,
		&i.LastAirAt,
	)
	return i, err
}

const deleteSeries = `-- name: DeleteSeries :exec
DELETE FROM series WHERE id = $1
`

func (q *Queries) DeleteSeries(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeries, id)
	return err
}

const deleteSeriesByTmdbId = `-- name: DeleteSeriesByTmdbId :exec
DELETE FROM series WHERE tmdb_id = $1 AND user_id = $2
`

type DeleteSeriesByTmdbIdParams struct {
	TmdbID uint64
	UserID uuid.UUID
}

func (q *Queries) DeleteSeriesByTmdbId(ctx context.Context, arg DeleteSeriesByTmdbIdParams) error {
	_, err := q.db.Exec(ctx, deleteSeriesByTmdbId, arg.TmdbID, arg.UserID)
	return err
}

const findEpisodeTmdbIdsBySeriesId = `-- name: FindEpisodeTmdbIdsBySeriesId :many
SELECT e.tmdb_id
FROM episodes e
  JOIN seasons s ON e.season_id = s.id
WHERE s.series_id = $1
`

func (q *Queries) FindEpisodeTmdbIdsBySeriesId(ctx context.Context, seriesID uuid.UUID) ([]uint64, error) {
	rows, err := q.db.Query(ctx, findEpisodeTmdbIdsBySeriesId, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uint64
	for rows.Next() {
		var tmdb_id uint64
		if err := rows.Scan(&tmdb_id); err != nil {
			return nil, err
		}
		items = append(items, tmdb_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSeriesById = `-- name: FindSeriesById :one
SELECT
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  pinned,
  created_at,
  updated_at,
  tracked_state,
  synced_at,
  last_air_at
FROM series
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindSeriesById(ctx context.Context, id uuid.UUID) (Series, error) {
	row := q.db.QueryRow(ctx, findSeriesById, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.SeasonsCount,
		&i.EpisodesCount,
		&i.Status,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackedState,
		&i.SyncedAt,
		&i.LastAirAt,
	)
	return i, err
}

const findSeriesByState = `-- name: FindSeriesByState :many
WITH counter AS (
  SELECT COUNT(*) AS total
  FROM series
  WHERE user_id = $1 AND state = $2
)
SELECT
  s.id,
  s.user_id,
  s.tmdb_id,
  s.title,
  s.poster_path,
  s.episodes_count,
  s.pinned,
  s.state,
  s.created_at,
  s.updated_at,
  counter.total,
  (
    SELECT COUNT(*)
    FROM episodes e
      JOIN seasons se ON e.season_id = se.id
    WHERE se.series_id = s.id
  )::bigint AS watched_episodes_count
FROM series s CROSS JOIN counter
WHERE s.user_id = $1 AND s.state = $2
ORDER BY s.pinned DESC, s.created_at DESC LIMIT $3 OFFSET $4
`

type FindSeriesByStateParams struct {
	UserID uuid.UUID
	State  StateTypes
	Limit  int32
	Offset int32
}

type FindSeriesByStateRow struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	TmdbID               uint64
	Title                string
	PosterPath           string
	EpisodesCount        uint64
	Pinned               bool
	State                StateTypes
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Total                int64
	WatchedEpisodesCount int64
}

func (q *Queries) FindSeriesByState(ctx context.Context, arg FindSeriesByStateParams) ([]FindSeriesByStateRow, error) {
	rows, err := q.db.Query(ctx, findSeriesByState,
		arg.UserID,
		arg.State,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSeriesByStateRow
	for rows.Next() {
		var i FindSeriesByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TmdbID,
			&i.Title,
			&i.PosterPath,
			&i.EpisodesCount,
			&i.Pinned,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
			&i.WatchedEpisodesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSeriesByTmdbId = `-- name: FindSeriesByTmdbId :one
SELECT
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  pinned,
  created_at,
  updated_at,
  tracked_state,
  synced_at,
  last_air_at
FROM series
WHERE tmdb_id = $1 AND user_id = $2 LIMIT 1
`

type FindSeriesByTmdbIdParams struct {
	TmdbID uint64
	UserID uuid.UUID
}

func (q *Queries) FindSeriesByTmdbId(ctx context.Context, arg FindSeriesByTmdbIdParams) (Series, error) {
	row := q.db.QueryRow(ctx, findSeriesByTmdbId, arg.TmdbID, arg.UserID)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.SeasonsCount,
		&i.EpisodesCount,
		&i.Status,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackedState,
		&i.SyncedAt,
		&i.LastAirAt,
	)
	return i, err
}

const findSeriesByTmdbIdForUpdate = `-- name: FindSeriesByTmdbIdForUpdate :one
SELECT
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  pinned,
  created_at,
  updated_at,
  tracked_state,
  synced_at,
  last_air_at
FROM series
WHERE tmdb_id = $1 AND user_id = $2 LIMIT 1
FOR UPDATE
`

type FindSeriesByTmdbIdForUpdateParams struct {
	TmdbID uint64
	UserID uuid.UUID
}

func (q *Queries) FindSeriesByTmdbIdForUpdate(ctx context.Context, arg FindSeriesByTmdbIdForUpdateParams) (Series, error) {
	row := q.db.QueryRow(ctx, findSeriesByTmdbIdForUpdate, arg.TmdbID, arg.UserID)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.SeasonsCount,
		&i.EpisodesCount,
		&i.Status,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackedState,
		&i.SyncedAt,
		&i.LastAirAt,
	)
	return i, err
}

const findSeriesByTmdbIds = `-- name: FindSeriesByTmdbIds :many
SELECT
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  pinned,
  created_at,
  updated_at,
  tracked_state,
  synced_at,
  last_air_at
FROM series
WHERE tmdb_id = ANY($1::integer[]) AND user_id = $2
`

type FindSeriesByTmdbIdsParams struct {
	TmdbIds []int32
	UserID  uuid.UUID
}

func (q *Queries) FindSeriesByTmdbIds(ctx context.Context, arg FindSeriesByTmdbIdsParams) ([]Series, error) {
	rows, err := q.db.Query(ctx, findSeriesByTmdbIds, arg.TmdbIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Series
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TmdbID,
			&i.Title,
			&i.PosterPath,
			&i.SeasonsCount,
			&i.EpisodesCount,
			&i.Status,
			&i.State,
			&i.Pinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrackedState,
			&i.SyncedAt,
			&i.LastAirAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSeriesToSync = `-- name: FindSeriesToSync :many
SELECT
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status
FROM series
WHERE (synced_at IS NULL OR synced_at < $1)
  AND (
    last_air_at IS NULL
    OR last_air_at >= $2
    OR status = ANY($3::varchar[])
  )
ORDER BY synced_at ASC NULLS FIRST
LIMIT $4
`

type FindSeriesToSyncParams struct {
	StaleBefore    pgtype.Timestamptz
	AirCutoff      pgtype.Timestamptz
	ActiveStatuses []string
	BatchSize      int32
}

type FindSeriesToSyncRow struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	TmdbID        uint64
	Title         string
	PosterPath    string
	SeasonsCount  uint64
	EpisodesCount uint64
	Status        string
}

func (q *Queries) FindSeriesToSync(ctx context.Context, arg FindSeriesToSyncParams) ([]FindSeriesToSyncRow, error) {
	rows, err := q.db.Query(ctx, findSeriesToSync,
		arg.StaleBefore,
		arg.AirCutoff,
		arg.ActiveStatuses,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindSeriesToSyncRow
	for rows.Next() {
		var i FindSeriesToSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TmdbID,
			&i.Title,
			&i.PosterPath,
			&i.SeasonsCount,
			&i.EpisodesCount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findWatchedSeasonTmdbIdsBySeriesId = `-- name: FindWatchedSeasonTmdbIdsBySeriesId :many
SELECT tmdb_id FROM seasons WHERE series_id = $1 AND state = 'watched'
`

func (q *Queries) FindWatchedSeasonTmdbIdsBySeriesId(ctx context.Context, seriesID uuid.UUID) ([]uint64, error) {
	rows, err := q.db.Query(ctx, findWatchedSeasonTmdbIdsBySeriesId, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uint64
	for rows.Next() {
		var tmdb_id uint64
		if err := rows.Scan(&tmdb_id); err != nil {
			return nil, err
		}
		items = append(items, tmdb_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSeriesState = `-- name: SetSeriesState :exec
UPDATE series SET state = $2, updated_at = NOW() WHERE id = $1
`

type SetSeriesStateParams struct {
	ID    uuid.UUID
	State StateTypes
}

func (q *Queries) SetSeriesState(ctx context.Context, arg SetSeriesStateParams) error {
	_, err := q.db.Exec(ctx, setSeriesState, arg.ID, arg.State)
	return err
}

const syncSeries = `-- name: SyncSeries :one
UPDATE series
SET
  title = $1,
  poster_path = $2,
  seasons_count = $3,
  episodes_count = $4,
  status = $5,
  last_air_at = $6,
  synced_at = NOW()
WHERE id = $7
RETURNING
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  pinned,
  created_at,
  updated_at,
  tracked_state,
  synced_at,
  last_air_at
`

type SyncSeriesParams struct {
	Title         string
	PosterPath    string
	SeasonsCount  uint64
	EpisodesCount uint64
	Status        string
	LastAirAt     pgtype.Timestamptz
	ID            uuid.UUID
}

func (q *Queries) SyncSeries(ctx context.Context, arg SyncSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, syncSeries,
		arg.Title,
		arg.PosterPath,
		arg.SeasonsCount,
		arg.EpisodesCount,
		arg.Status,
		arg.LastAirAt,
		arg.ID,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.SeasonsCount,
		&i.EpisodesCount,
		&i.Status,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackedState,
		&i.SyncedAt,
		&i.LastAirAt,
	)
	return i, err
}

const touchSeriesSynced = `-- name: TouchSeriesSynced :exec
UPDATE series SET synced_at = NOW() WHERE id = $1
`

func (q *Queries) TouchSeriesSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSeriesSynced, id)
	return err
}

const updateSeries = `-- name: UpdateSeries :one
UPDATE series
SET
  title = $2,
  poster_path = $3,
  seasons_count = $4,
  episodes_count = $5,
  status = $6,
  updated_at = NOW()
WHERE id = $1
RETURNING
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  pinned,
  created_at,
  updated_at,
  tracked_state,
  synced_at,
  last_air_at
`

type UpdateSeriesParams struct {
	ID            uuid.UUID
	Title         string
	PosterPath    string
	SeasonsCount  uint64
	EpisodesCount uint64
	Status        string
}

func (q *Queries) UpdateSeries(ctx context.Context, arg UpdateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, updateSeries,
		arg.ID,
		arg.Title,
		arg.PosterPath,
		arg.SeasonsCount,
		arg.EpisodesCount,
		arg.Status,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.SeasonsCount,
		&i.EpisodesCount,
		&i.Status,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackedState,
		&i.SyncedAt,
		&i.LastAirAt,
	)
	return i, err
}

const updateSeriesByTmdbId = `-- name: UpdateSeriesByTmdbId :one
UPDATE series
SET
  state = $3,
  tracked_state = $3,
  pinned = $4,
  updated_at = NOW()
WHERE tmdb_id = $1 AND user_id = $2
RETURNING
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  pinned,
  created_at,
  updated_at,
  tracked_state,
  synced_at,
  last_air_at
`

type UpdateSeriesByTmdbIdParams struct {
	TmdbID uint64
	UserID uuid.UUID
	State  StateTypes
	Pinned bool
}

func (q *Queries) UpdateSeriesByTmdbId(ctx context.Context, arg UpdateSeriesByTmdbIdParams) (Series, error) {
	row := q.db.QueryRow(ctx, updateSeriesByTmdbId,
		arg.TmdbID,
		arg.UserID,
		arg.State,
		arg.Pinned,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.SeasonsCount,
		&i.EpisodesCount,
		&i.Status,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackedState,
		&i.SyncedAt,
		&i.LastAirAt,
	)
	return i, err
}

const upsertSeries = `-- name: UpsertSeries :one
INSERT INTO series (
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (user_id, tmdb_id) DO UPDATE SET
  title = EXCLUDED.title,
  poster_path = EXCLUDED.poster_path,
  seasons_count = CASE WHEN EXCLUDED.seasons_count > 0 THEN EXCLUDED.seasons_count ELSE series.seasons_count END,
  episodes_count = CASE WHEN EXCLUDED.episodes_count > 0 THEN EXCLUDED.episodes_count ELSE series.episodes_count END,
  status = EXCLUDED.status,
  updated_at = NOW()
RETURNING
  id,
  user_id,
  tmdb_id,
  title,
  poster_path,
  seasons_count,
  episodes_count,
  status,
  state,
  pinned,
  created_at,
  updated_at,
  tracked_state,
  synced_at,
  last_air_at
`

type UpsertSeriesParams struct {
	UserID        uuid.UUID
	TmdbID        uint64
	Title         string
	PosterPath    string
	SeasonsCount  uint64
	EpisodesCount uint64
	Status        string
	State         StateTypes
}

func (q *Queries) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, upsertSeries,
		arg.UserID,
		arg.TmdbID,
		arg.Title,
		arg.PosterPath,
		arg.SeasonsCount,
		arg.EpisodesCount,
		arg.Status,
		arg.State,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TmdbID,
		&i.Title,
		&i.PosterPath,
		&i.SeasonsCount,
		&i.EpisodesCount,
		&i.Status,
		&i.State,
		&i.Pinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrackedState,
		&i.SyncedAt,
		&i.LastAirAt,
	)
	return i, err
}
