// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const episodeStats = `-- name: EpisodeStats :one
SELECT
  COUNT(*)::bigint AS watched_count,
  COALESCE(SUM(e.runtime), 0)::bigint AS watched_minutes
FROM episodes e
  JOIN seasons s ON e.season_id = s.id
  JOIN series t ON s.series_id = t.id
WHERE t.user_id = $1
  AND e.watched_at >= date_trunc($2::text, NOW())
`

type EpisodeStatsParams struct {
	UserID     uuid.UUID
	PeriodUnit string
}

type EpisodeStatsRow struct {
	WatchedCount   int64
	WatchedMinutes int64
}

// Episode rows only exist while watched, so the period filters on watched_at alone
func (q *Queries) EpisodeStats(ctx context.Context, arg EpisodeStatsParams) (EpisodeStatsRow, error) {
	row := q.db.QueryRow(ctx, episodeStats, arg.UserID, arg.PeriodUnit)
	var i EpisodeStatsRow
	err := row.Scan(&i.WatchedCount, &i.WatchedMinutes)
	return i, err
}

const episodeStatsAll = `-- name: EpisodeStatsAll :one
SELECT
  COUNT(*)::bigint AS watched_count,
  COALESCE(SUM(e.runtime), 0)::bigint AS watched_minutes
FROM episodes e
  JOIN seasons s ON e.season_id = s.id
  JOIN series t ON s.series_id = t.id
WHERE t.user_id = $1
`

type EpisodeStatsAllRow struct {
	WatchedCount   int64
	WatchedMinutes int64
}

func (q *Queries) EpisodeStatsAll(ctx context.Context, userID uuid.UUID) (EpisodeStatsAllRow, error) {
	row := q.db.QueryRow(ctx, episodeStatsAll, userID)
	var i EpisodeStatsAllRow
	err := row.Scan(&i.WatchedCount, &i.WatchedMinutes)
	return i, err
}

const movieStats = `-- name: MovieStats :one

WITH bound AS (
  SELECT date_trunc($2::text, NOW()) AS since
)
SELECT
  COUNT(*) FILTER (WHERE state = 'want')::bigint AS want_count,
  COUNT(*) FILTER (WHERE state = 'watched' AND watched_at >= (SELECT since FROM bound))::bigint AS watched_count,
  COALESCE(SUM(runtime) FILTER (WHERE state = 'watched' AND watched_at >= (SELECT since FROM bound)), 0)::bigint AS watched_minutes
FROM movies
WHERE user_id = $1
`

type MovieStatsParams struct {
	UserID     uuid.UUID
	PeriodUnit string
}

type MovieStatsRow struct {
	WantCount      int64
	WatchedCount   int64
	WatchedMinutes int64
}

// Watched stats come in pairs: a bounded query for the current calendar period and
// an all-time one. Serving both from a single statement with a nullable bound makes
// postgres settle on a generic plan that never uses the watched_at indexes.
// Want is all-time; watched counts and minutes cover the current period. The bound
// lives in a CTE so it is computed once rather than per row
func (q *Queries) MovieStats(ctx context.Context, arg MovieStatsParams) (MovieStatsRow, error) {
	row := q.db.QueryRow(ctx, movieStats, arg.UserID, arg.PeriodUnit)
	var i MovieStatsRow
	err := row.Scan(&i.WantCount, &i.WatchedCount, &i.WatchedMinutes)
	return i, err
}

const movieStatsAll = `-- name: MovieStatsAll :one
SELECT
  COUNT(*) FILTER (WHERE state = 'want')::bigint AS want_count,
  COUNT(*) FILTER (WHERE state = 'watched')::bigint AS watched_count,
  COALESCE(SUM(runtime) FILTER (WHERE state = 'watched'), 0)::bigint AS watched_minutes
FROM movies
WHERE user_id = $1
`

type MovieStatsAllRow struct {
	WantCount      int64
	WatchedCount   int64
	WatchedMinutes int64
}

func (q *Queries) MovieStatsAll(ctx context.Context, userID uuid.UUID) (MovieStatsAllRow, error) {
	row := q.db.QueryRow(ctx, movieStatsAll, userID)
	var i MovieStatsAllRow
	err := row.Scan(&i.WantCount, &i.WatchedCount, &i.WatchedMinutes)
	return i, err
}

const seriesStats = `-- name: SeriesStats :one
SELECT
  COUNT(*) FILTER (WHERE state = 'want')::bigint AS want_count,
  COUNT(*) FILTER (WHERE state = 'watching')::bigint AS watching_count,
  COUNT(*) FILTER (WHERE state = 'watched')::bigint AS watched_count
FROM series
WHERE user_id = $1
`

type SeriesStatsRow struct {
	WantCount     int64
	WatchingCount int64
	WatchedCount  int64
}

func (q *Queries) SeriesStats(ctx context.Context, userID uuid.UUID) (SeriesStatsRow, error) {
	row := q.db.QueryRow(ctx, seriesStats, userID)
	var i SeriesStatsRow
	err := row.Scan(&i.WantCount, &i.WatchingCount, &i.WatchedCount)
	return i, err
}

const watchActivity = `-- name: WatchActivity :many
WITH bound AS (
  SELECT
    date_trunc($1::text, NOW()) AS since,
    CASE $1::text
      WHEN 'week' THEN INTERVAL '1 week'
      WHEN 'month' THEN INTERVAL '1 month'
      ELSE INTERVAL '1 year'
    END AS span,
    -- bounded periods only ever bucket by day or month
    CASE $2::text
      WHEN 'day' THEN INTERVAL '1 day'
      ELSE INTERVAL '1 month'
    END AS step
),
watched AS (
  SELECT mv.watched_at AS watched_at, mv.runtime AS minutes, 'movie' AS kind
  FROM movies mv
  WHERE mv.user_id = $3
    AND mv.watched_at >= (SELECT since FROM bound)
  UNION ALL
  SELECT e.watched_at AS watched_at, e.runtime AS minutes, 'tv' AS kind
  FROM episodes e
    JOIN seasons s ON e.season_id = s.id
    JOIN series t ON s.series_id = t.id
  WHERE t.user_id = $3
    AND e.watched_at >= (SELECT since FROM bound)
),
totals AS (
  SELECT
    date_trunc($2::text, w.watched_at) AS bucket,
    SUM(w.minutes) FILTER (WHERE w.kind = 'movie') AS movie_minutes,
    SUM(w.minutes) FILTER (WHERE w.kind = 'tv') AS tv_minutes
  FROM watched w
  GROUP BY 1
)
SELECT
  b.bucket::date AS bucket,
  COALESCE(t.movie_minutes, 0)::bigint AS movie_minutes,
  COALESCE(t.tv_minutes, 0)::bigint AS tv_minutes
FROM bound
  CROSS JOIN LATERAL generate_series(since, since + span - step, step) AS b(bucket)
  LEFT JOIN totals t ON t.bucket = b.bucket
ORDER BY b.bucket
`

type WatchActivityParams struct {
	PeriodUnit string
	BucketUnit string
	UserID     uuid.UUID
}

type WatchActivityRow struct {
	Bucket       pgtype.Date
	MovieMinutes int64
	TvMinutes    int64
}

// Watched minutes per bucket, split into movie and TV runtime and dense (buckets
// with no activity return zero). Buckets span the whole current calendar period --
// Monday to Sunday, the 1st to the end of the month, January to December -- so the
// rest of an unfinished period reads as empty.
func (q *Queries) WatchActivity(ctx context.Context, arg WatchActivityParams) ([]WatchActivityRow, error) {
	rows, err := q.db.Query(ctx, watchActivity, arg.PeriodUnit, arg.BucketUnit, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchActivityRow
	for rows.Next() {
		var i WatchActivityRow
		if err := rows.Scan(&i.Bucket, &i.MovieMinutes, &i.TvMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const watchActivityAll = `-- name: WatchActivityAll :many
WITH watched AS (
  SELECT mv.watched_at AS watched_at, mv.runtime AS minutes, 'movie' AS kind
  FROM movies mv
  WHERE mv.user_id = $1 AND mv.watched_at IS NOT NULL
  UNION ALL
  SELECT e.watched_at AS watched_at, e.runtime AS minutes, 'tv' AS kind
  FROM episodes e
    JOIN seasons s ON e.season_id = s.id
    JOIN series t ON s.series_id = t.id
  WHERE t.user_id = $1 AND e.watched_at IS NOT NULL
),
totals AS (
  SELECT
    date_trunc('year', w.watched_at) AS bucket,
    SUM(w.minutes) FILTER (WHERE w.kind = 'movie') AS movie_minutes,
    SUM(w.minutes) FILTER (WHERE w.kind = 'tv') AS tv_minutes
  FROM watched w
  GROUP BY 1
),
buckets AS (
  -- the earliest bucket comes from the yearly totals rather than a second pass
  -- over every watch, which leaves the history read exactly once
  SELECT generate_series(
    COALESCE((SELECT MIN(bucket) FROM totals), date_trunc('year', NOW())),
    date_trunc('year', NOW()),
    INTERVAL '1 year'
  ) AS bucket
)
SELECT
  b.bucket::date AS bucket,
  COALESCE(t.movie_minutes, 0)::bigint AS movie_minutes,
  COALESCE(t.tv_minutes, 0)::bigint AS tv_minutes
FROM buckets b
  LEFT JOIN totals t ON t.bucket = b.bucket
ORDER BY b.bucket
`

type WatchActivityAllRow struct {
	Bucket       pgtype.Date
	MovieMinutes int64
	TvMinutes    int64
}

// Watched minutes per year across the whole history, dense and split by media kind
func (q *Queries) WatchActivityAll(ctx context.Context, userID uuid.UUID) ([]WatchActivityAllRow, error) {
	rows, err := q.db.Query(ctx, watchActivityAll, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchActivityAllRow
	for rows.Next() {
		var i WatchActivityAllRow
		if err := rows.Scan(&i.Bucket, &i.MovieMinutes, &i.TvMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
