// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :exec
INSERT INTO webhooks (
  integration_id,
  payload,
  status,
  error
) VALUES (
  $1, $2, $3, $4
)
`

type CreateWebhookParams struct {
	IntegrationID uuid.UUID
	Payload       []byte
	Status        StatusType
	Error         pgtype.Text
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) error {
	_, err := q.db.Exec(ctx, createWebhook,
		arg.IntegrationID,
		arg.Payload,
		arg.Status,
		arg.Error,
	)
	return err
}
