disabled_rules:
  - trailing_comma
  - todo

line_length:
  warning: 140
  error: 200

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 300
  error: 400

identifier_name:
  min_length: 2

excluded:
  - build
