// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/games.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/games.go -destination=internal/app/services/games_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGames is a mock of Games interface.
type MockGames struct {
	ctrl     *gomock.Controller
	recorder *MockGamesMockRecorder
	isgomock struct{}
}

// MockGamesMockRecorder is the mock recorder for MockGames.
type MockGamesMockRecorder struct {
	mock *MockGames
}

// NewMockGames creates a new mock instance.
func NewMockGames(ctrl *gomock.Controller) *MockGames {
	mock := &MockGames{ctrl: ctrl}
	mock.recorder = &MockGamesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGames) EXPECT() *MockGamesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGames) Create(ctx context.Context, params *models.Game) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGamesMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGames)(nil).Create), ctx, params)
}

// DeleteByIgdbId mocks base method.
func (m *MockGames) DeleteByIgdbId(ctx context.Context, igdbId uint64, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIgdbId", ctx, igdbId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIgdbId indicates an expected call of DeleteByIgdbId.
func (mr *MockGamesMockRecorder) DeleteByIgdbId(ctx, igdbId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIgdbId", reflect.TypeOf((*MockGames)(nil).DeleteByIgdbId), ctx, igdbId, userId)
}

// FindByIgdbId mocks base method.
func (m *MockGames) FindByIgdbId(ctx context.Context, igdbId uint64, userId uuid.UUID) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIgdbId", ctx, igdbId, userId)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIgdbId indicates an expected call of FindByIgdbId.
func (mr *MockGamesMockRecorder) FindByIgdbId(ctx, igdbId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIgdbId", reflect.TypeOf((*MockGames)(nil).FindByIgdbId), ctx, igdbId, userId)
}

// FindGamesByIgdbIds mocks base method.
func (m *MockGames) FindGamesByIgdbIds(ctx context.Context, igdbIds []uint64, userId uuid.UUID) ([]models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGamesByIgdbIds", ctx, igdbIds, userId)
	ret0, _ := ret[0].([]models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGamesByIgdbIds indicates an expected call of FindGamesByIgdbIds.
func (mr *MockGamesMockRecorder) FindGamesByIgdbIds(ctx, igdbIds, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGamesByIgdbIds", reflect.TypeOf((*MockGames)(nil).FindGamesByIgdbIds), ctx, igdbIds, userId)
}

// List mocks base method.
func (m *MockGames) List(ctx context.Context, userId uuid.UUID, state models.StateType, pagination *Pagination) ([]models.Game, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userId, state, pagination)
	ret0, _ := ret[0].([]models.Game)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockGamesMockRecorder) List(ctx, userId, state, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGames)(nil).List), ctx, userId, state, pagination)
}

// Update mocks base method.
func (m *MockGames) Update(ctx context.Context, params *models.Game) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGamesMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGames)(nil).Update), ctx, params)
}

// UpdateByIgdbId mocks base method.
func (m *MockGames) UpdateByIgdbId(ctx context.Context, params *models.Game) (*models.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByIgdbId", ctx, params)
	ret0, _ := ret[0].(*models.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByIgdbId indicates an expected call of UpdateByIgdbId.
func (mr *MockGamesMockRecorder) UpdateByIgdbId(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByIgdbId", reflect.TypeOf((*MockGames)(nil).UpdateByIgdbId), ctx, params)
}
