// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/igdb.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/igdb.go -destination=internal/app/services/igdb_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	serializers "biinge-api/internal/app/serializers"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIgdbProvider is a mock of IgdbProvider interface.
type MockIgdbProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIgdbProviderMockRecorder
	isgomock struct{}
}

// MockIgdbProviderMockRecorder is the mock recorder for MockIgdbProvider.
type MockIgdbProviderMockRecorder struct {
	mock *MockIgdbProvider
}

// NewMockIgdbProvider creates a new mock instance.
func NewMockIgdbProvider(ctrl *gomock.Controller) *MockIgdbProvider {
	mock := &MockIgdbProvider{ctrl: ctrl}
	mock.recorder = &MockIgdbProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIgdbProvider) EXPECT() *MockIgdbProviderMockRecorder {
	return m.recorder
}

// FetchGameDetails mocks base method.
func (m *MockIgdbProvider) FetchGameDetails(ctx context.Context, id uint64, userId uuid.UUID) (*serializers.GameDetailsSerializer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGameDetails", ctx, id, userId)
	ret0, _ := ret[0].(*serializers.GameDetailsSerializer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGameDetails indicates an expected call of FetchGameDetails.
func (mr *MockIgdbProviderMockRecorder) FetchGameDetails(ctx, id, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGameDetails", reflect.TypeOf((*MockIgdbProvider)(nil).FetchGameDetails), ctx, id, userId)
}

// FetchTrendingGames mocks base method.
func (m *MockIgdbProvider) FetchTrendingGames(ctx context.Context, userId uuid.UUID) (*serializers.PaginationResponse[serializers.SearchGameSerializer], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTrendingGames", ctx, userId)
	ret0, _ := ret[0].(*serializers.PaginationResponse[serializers.SearchGameSerializer])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTrendingGames indicates an expected call of FetchTrendingGames.
func (mr *MockIgdbProviderMockRecorder) FetchTrendingGames(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTrendingGames", reflect.TypeOf((*MockIgdbProvider)(nil).FetchTrendingGames), ctx, userId)
}

// FetchUpNextGames mocks base method.
func (m *MockIgdbProvider) FetchUpNextGames(ctx context.Context, userId uuid.UUID) ([]serializers.UpNextGameSerializer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchUpNextGames", ctx, userId)
	ret0, _ := ret[0].([]serializers.UpNextGameSerializer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchUpNextGames indicates an expected call of FetchUpNextGames.
func (mr *MockIgdbProviderMockRecorder) FetchUpNextGames(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchUpNextGames", reflect.TypeOf((*MockIgdbProvider)(nil).FetchUpNextGames), ctx, userId)
}

// SearchGames mocks base method.
func (m *MockIgdbProvider) SearchGames(ctx context.Context, query string, page uint64, userId uuid.UUID) (*serializers.PaginationResponse[serializers.SearchGameSerializer], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchGames", ctx, query, page, userId)
	ret0, _ := ret[0].(*serializers.PaginationResponse[serializers.SearchGameSerializer])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchGames indicates an expected call of SearchGames.
func (mr *MockIgdbProviderMockRecorder) SearchGames(ctx, query, page, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchGames", reflect.TypeOf((*MockIgdbProvider)(nil).SearchGames), ctx, query, page, userId)
}
