// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/integrations.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/integrations.go -destination=internal/app/services/integrations_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIntegrations is a mock of Integrations interface.
type MockIntegrations struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationsMockRecorder
	isgomock struct{}
}

// MockIntegrationsMockRecorder is the mock recorder for MockIntegrations.
type MockIntegrationsMockRecorder struct {
	mock *MockIntegrations
}

// NewMockIntegrations creates a new mock instance.
func NewMockIntegrations(ctrl *gomock.Controller) *MockIntegrations {
	mock := &MockIntegrations{ctrl: ctrl}
	mock.recorder = &MockIntegrationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegrations) EXPECT() *MockIntegrationsMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockIntegrations) Authenticate(ctx context.Context, token string) (*models.Integration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, token)
	ret0, _ := ret[0].(*models.Integration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockIntegrationsMockRecorder) Authenticate(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockIntegrations)(nil).Authenticate), ctx, token)
}

// CreateToken mocks base method.
func (m *MockIntegrations) CreateToken(ctx context.Context, userId uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockIntegrationsMockRecorder) CreateToken(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockIntegrations)(nil).CreateToken), ctx, userId)
}

// Revoke mocks base method.
func (m *MockIntegrations) Revoke(ctx context.Context, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockIntegrationsMockRecorder) Revoke(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockIntegrations)(nil).Revoke), ctx, userId)
}
