// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/jellyfin.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/jellyfin.go -destination=internal/app/services/jellyfin_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	models "biinge-api/internal/app/models"
	jellyfin "biinge-api/pkg/jellyfin"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJellyfin is a mock of Jellyfin interface.
type MockJellyfin struct {
	ctrl     *gomock.Controller
	recorder *MockJellyfinMockRecorder
	isgomock struct{}
}

// MockJellyfinMockRecorder is the mock recorder for MockJellyfin.
type MockJellyfinMockRecorder struct {
	mock *MockJellyfin
}

// NewMockJellyfin creates a new mock instance.
func NewMockJellyfin(ctrl *gomock.Controller) *MockJellyfin {
	mock := &MockJellyfin{ctrl: ctrl}
	mock.recorder = &MockJellyfinMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJellyfin) EXPECT() *MockJellyfinMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockJellyfin) Handle(ctx context.Context, integration *models.Integration, event *jellyfin.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, integration, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockJellyfinMockRecorder) Handle(ctx, integration, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockJellyfin)(nil).Handle), ctx, integration, event)
}
