// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/movies.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/movies.go -destination=internal/app/services/movies_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMovies is a mock of Movies interface.
type MockMovies struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesMockRecorder
	isgomock struct{}
}

// MockMoviesMockRecorder is the mock recorder for MockMovies.
type MockMoviesMockRecorder struct {
	mock *MockMovies
}

// NewMockMovies creates a new mock instance.
func NewMockMovies(ctrl *gomock.Controller) *MockMovies {
	mock := &MockMovies{ctrl: ctrl}
	mock.recorder = &MockMoviesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovies) EXPECT() *MockMoviesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMovies) Create(ctx context.Context, params *models.Movie) (*models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*models.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMoviesMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMovies)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockMovies) Delete(ctx context.Context, tmdbId uint64, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tmdbId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMoviesMockRecorder) Delete(ctx, tmdbId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMovies)(nil).Delete), ctx, tmdbId, userId)
}

// FindByFilter mocks base method.
func (m *MockMovies) FindByFilter(ctx context.Context, filter models.MovieFilter) ([]models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", ctx, filter)
	ret0, _ := ret[0].([]models.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockMoviesMockRecorder) FindByFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockMovies)(nil).FindByFilter), ctx, filter)
}

// List mocks base method.
func (m *MockMovies) List(ctx context.Context, userId uuid.UUID, state models.StateType, pagination *Pagination) ([]models.Movie, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userId, state, pagination)
	ret0, _ := ret[0].([]models.Movie)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockMoviesMockRecorder) List(ctx, userId, state, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMovies)(nil).List), ctx, userId, state, pagination)
}

// Update mocks base method.
func (m *MockMovies) Update(ctx context.Context, params *models.Movie) (*models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*models.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMoviesMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMovies)(nil).Update), ctx, params)
}

// UpdateByTmdbId mocks base method.
func (m *MockMovies) UpdateByTmdbId(ctx context.Context, params *models.Movie) (*models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTmdbId", ctx, params)
	ret0, _ := ret[0].(*models.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByTmdbId indicates an expected call of UpdateByTmdbId.
func (mr *MockMoviesMockRecorder) UpdateByTmdbId(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTmdbId", reflect.TypeOf((*MockMovies)(nil).UpdateByTmdbId), ctx, params)
}
