// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/progress.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/progress.go -destination=internal/app/services/progress_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProgress is a mock of Progress interface.
type MockProgress struct {
	ctrl     *gomock.Controller
	recorder *MockProgressMockRecorder
	isgomock struct{}
}

// MockProgressMockRecorder is the mock recorder for MockProgress.
type MockProgressMockRecorder struct {
	mock *MockProgress
}

// NewMockProgress creates a new mock instance.
func NewMockProgress(ctrl *gomock.Controller) *MockProgress {
	mock := &MockProgress{ctrl: ctrl}
	mock.recorder = &MockProgressMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgress) EXPECT() *MockProgressMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProgress) Get(ctx context.Context, userId uuid.UUID, seriesTmdbId uint64) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userId, seriesTmdbId)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProgressMockRecorder) Get(ctx, userId, seriesTmdbId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProgress)(nil).Get), ctx, userId, seriesTmdbId)
}

// MarkEpisode mocks base method.
func (m *MockProgress) MarkEpisode(ctx context.Context, userId uuid.UUID, series models.SeriesInput, season models.SeasonInput, episode models.EpisodeInput) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEpisode", ctx, userId, series, season, episode)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEpisode indicates an expected call of MarkEpisode.
func (mr *MockProgressMockRecorder) MarkEpisode(ctx, userId, series, season, episode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEpisode", reflect.TypeOf((*MockProgress)(nil).MarkEpisode), ctx, userId, series, season, episode)
}

// MarkSeason mocks base method.
func (m *MockProgress) MarkSeason(ctx context.Context, userId uuid.UUID, series models.SeriesInput, season models.SeasonInput) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSeason", ctx, userId, series, season)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkSeason indicates an expected call of MarkSeason.
func (mr *MockProgressMockRecorder) MarkSeason(ctx, userId, series, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSeason", reflect.TypeOf((*MockProgress)(nil).MarkSeason), ctx, userId, series, season)
}

// MarkShow mocks base method.
func (m *MockProgress) MarkShow(ctx context.Context, userId uuid.UUID, show models.ShowInput) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkShow", ctx, userId, show)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkShow indicates an expected call of MarkShow.
func (mr *MockProgressMockRecorder) MarkShow(ctx, userId, show any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkShow", reflect.TypeOf((*MockProgress)(nil).MarkShow), ctx, userId, show)
}

// UnmarkEpisode mocks base method.
func (m *MockProgress) UnmarkEpisode(ctx context.Context, userId uuid.UUID, seriesTmdbId, seasonTmdbId, episodeTmdbId uint64) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarkEpisode", ctx, userId, seriesTmdbId, seasonTmdbId, episodeTmdbId)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarkEpisode indicates an expected call of UnmarkEpisode.
func (mr *MockProgressMockRecorder) UnmarkEpisode(ctx, userId, seriesTmdbId, seasonTmdbId, episodeTmdbId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarkEpisode", reflect.TypeOf((*MockProgress)(nil).UnmarkEpisode), ctx, userId, seriesTmdbId, seasonTmdbId, episodeTmdbId)
}

// UnmarkSeason mocks base method.
func (m *MockProgress) UnmarkSeason(ctx context.Context, userId uuid.UUID, seriesTmdbId, seasonTmdbId uint64) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarkSeason", ctx, userId, seriesTmdbId, seasonTmdbId)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarkSeason indicates an expected call of UnmarkSeason.
func (mr *MockProgressMockRecorder) UnmarkSeason(ctx, userId, seriesTmdbId, seasonTmdbId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarkSeason", reflect.TypeOf((*MockProgress)(nil).UnmarkSeason), ctx, userId, seriesTmdbId, seasonTmdbId)
}

// UnmarkShow mocks base method.
func (m *MockProgress) UnmarkShow(ctx context.Context, userId uuid.UUID, seriesTmdbId uint64) (*models.SeriesProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarkShow", ctx, userId, seriesTmdbId)
	ret0, _ := ret[0].(*models.SeriesProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarkShow indicates an expected call of UnmarkShow.
func (mr *MockProgressMockRecorder) UnmarkShow(ctx, userId, seriesTmdbId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarkShow", reflect.TypeOf((*MockProgress)(nil).UnmarkShow), ctx, userId, seriesTmdbId)
}
