// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/series.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/series.go -destination=internal/app/services/series_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSeries is a mock of Series interface.
type MockSeries struct {
	ctrl     *gomock.Controller
	recorder *MockSeriesMockRecorder
	isgomock struct{}
}

// MockSeriesMockRecorder is the mock recorder for MockSeries.
type MockSeriesMockRecorder struct {
	mock *MockSeries
}

// NewMockSeries creates a new mock instance.
func NewMockSeries(ctrl *gomock.Controller) *MockSeries {
	mock := &MockSeries{ctrl: ctrl}
	mock.recorder = &MockSeriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeries) EXPECT() *MockSeriesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSeries) Create(ctx context.Context, params *models.Series) (*models.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*models.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSeriesMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSeries)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockSeries) Delete(ctx context.Context, tmdbId uint64, userId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tmdbId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSeriesMockRecorder) Delete(ctx, tmdbId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSeries)(nil).Delete), ctx, tmdbId, userId)
}

// FindByFilter mocks base method.
func (m *MockSeries) FindByFilter(ctx context.Context, filter models.SeriesFilter) ([]models.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", ctx, filter)
	ret0, _ := ret[0].([]models.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockSeriesMockRecorder) FindByFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockSeries)(nil).FindByFilter), ctx, filter)
}

// List mocks base method.
func (m *MockSeries) List(ctx context.Context, userId uuid.UUID, state models.StateType, pagination *Pagination) ([]models.Series, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userId, state, pagination)
	ret0, _ := ret[0].([]models.Series)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSeriesMockRecorder) List(ctx, userId, state, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSeries)(nil).List), ctx, userId, state, pagination)
}

// Update mocks base method.
func (m *MockSeries) Update(ctx context.Context, params *models.Series) (*models.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*models.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSeriesMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSeries)(nil).Update), ctx, params)
}

// UpdateByTmdbId mocks base method.
func (m *MockSeries) UpdateByTmdbId(ctx context.Context, params *models.Series) (*models.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTmdbId", ctx, params)
	ret0, _ := ret[0].(*models.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByTmdbId indicates an expected call of UpdateByTmdbId.
func (mr *MockSeriesMockRecorder) UpdateByTmdbId(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTmdbId", reflect.TypeOf((*MockSeries)(nil).UpdateByTmdbId), ctx, params)
}
