// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/stats_cache.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/stats_cache.go -destination=internal/app/services/stats_cache_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	models "biinge-api/internal/app/models"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsCache is a mock of StatsCache interface.
type MockStatsCache struct {
	ctrl     *gomock.Controller
	recorder *MockStatsCacheMockRecorder
	isgomock struct{}
}

// MockStatsCacheMockRecorder is the mock recorder for MockStatsCache.
type MockStatsCacheMockRecorder struct {
	mock *MockStatsCache
}

// NewMockStatsCache creates a new mock instance.
func NewMockStatsCache(ctrl *gomock.Controller) *MockStatsCache {
	mock := &MockStatsCache{ctrl: ctrl}
	mock.recorder = &MockStatsCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsCache) EXPECT() *MockStatsCacheMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockStatsCache) Fetch(ctx context.Context, userId uuid.UUID, period models.StatsPeriod, source func() (*models.Stats, error)) (*models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, userId, period, source)
	ret0, _ := ret[0].(*models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockStatsCacheMockRecorder) Fetch(ctx, userId, period, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockStatsCache)(nil).Fetch), ctx, userId, period, source)
}

// Invalidate mocks base method.
func (m *MockStatsCache) Invalidate(ctx context.Context, userId uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Invalidate", ctx, userId)
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockStatsCacheMockRecorder) Invalidate(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockStatsCache)(nil).Invalidate), ctx, userId)
}
