// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/services/tmdb.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/services/tmdb.go -destination=internal/app/services/tmdb_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	serializers "biinge-api/internal/app/serializers"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTmdbProvider is a mock of TmdbProvider interface.
type MockTmdbProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTmdbProviderMockRecorder
	isgomock struct{}
}

// MockTmdbProviderMockRecorder is the mock recorder for MockTmdbProvider.
type MockTmdbProviderMockRecorder struct {
	mock *MockTmdbProvider
}

// NewMockTmdbProvider creates a new mock instance.
func NewMockTmdbProvider(ctrl *gomock.Controller) *MockTmdbProvider {
	mock := &MockTmdbProvider{ctrl: ctrl}
	mock.recorder = &MockTmdbProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTmdbProvider) EXPECT() *MockTmdbProviderMockRecorder {
	return m.recorder
}

// FetchMovieDetails mocks base method.
func (m *MockTmdbProvider) FetchMovieDetails(ctx context.Context, id uint64, userId uuid.UUID) (*serializers.MovieDetailsSerializer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMovieDetails", ctx, id, userId)
	ret0, _ := ret[0].(*serializers.MovieDetailsSerializer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMovieDetails indicates an expected call of FetchMovieDetails.
func (mr *MockTmdbProviderMockRecorder) FetchMovieDetails(ctx, id, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMovieDetails", reflect.TypeOf((*MockTmdbProvider)(nil).FetchMovieDetails), ctx, id, userId)
}

// FetchPersonDetails mocks base method.
func (m *MockTmdbProvider) FetchPersonDetails(ctx context.Context, id uint64, userId uuid.UUID) (*serializers.PersonDetailsSerializer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPersonDetails", ctx, id, userId)
	ret0, _ := ret[0].(*serializers.PersonDetailsSerializer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPersonDetails indicates an expected call of FetchPersonDetails.
func (mr *MockTmdbProviderMockRecorder) FetchPersonDetails(ctx, id, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPersonDetails", reflect.TypeOf((*MockTmdbProvider)(nil).FetchPersonDetails), ctx, id, userId)
}

// FetchTrendingMovies mocks base method.
func (m *MockTmdbProvider) FetchTrendingMovies(ctx context.Context, userId uuid.UUID) (*serializers.PaginationResponse[serializers.SearchMovieSerializer], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTrendingMovies", ctx, userId)
	ret0, _ := ret[0].(*serializers.PaginationResponse[serializers.SearchMovieSerializer])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTrendingMovies indicates an expected call of FetchTrendingMovies.
func (mr *MockTmdbProviderMockRecorder) FetchTrendingMovies(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTrendingMovies", reflect.TypeOf((*MockTmdbProvider)(nil).FetchTrendingMovies), ctx, userId)
}

// FetchTrendingPeople mocks base method.
func (m *MockTmdbProvider) FetchTrendingPeople(ctx context.Context) (*serializers.PaginationResponse[serializers.SearchPersonSerializer], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTrendingPeople", ctx)
	ret0, _ := ret[0].(*serializers.PaginationResponse[serializers.SearchPersonSerializer])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTrendingPeople indicates an expected call of FetchTrendingPeople.
func (mr *MockTmdbProviderMockRecorder) FetchTrendingPeople(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTrendingPeople", reflect.TypeOf((*MockTmdbProvider)(nil).FetchTrendingPeople), ctx)
}

// FetchTrendingSeries mocks base method.
func (m *MockTmdbProvider) FetchTrendingSeries(ctx context.Context, userId uuid.UUID) (*serializers.PaginationResponse[serializers.SearchSeriesSerializer], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTrendingSeries", ctx, userId)
	ret0, _ := ret[0].(*serializers.PaginationResponse[serializers.SearchSeriesSerializer])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTrendingSeries indicates an expected call of FetchTrendingSeries.
func (mr *MockTmdbProviderMockRecorder) FetchTrendingSeries(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTrendingSeries", reflect.TypeOf((*MockTmdbProvider)(nil).FetchTrendingSeries), ctx, userId)
}

// FetchTvDetails mocks base method.
func (m *MockTmdbProvider) FetchTvDetails(ctx context.Context, id uint64, userId uuid.UUID) (*serializers.SeriesDetailsSerializer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTvDetails", ctx, id, userId)
	ret0, _ := ret[0].(*serializers.SeriesDetailsSerializer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTvDetails indicates an expected call of FetchTvDetails.
func (mr *MockTmdbProviderMockRecorder) FetchTvDetails(ctx, id, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTvDetails", reflect.TypeOf((*MockTmdbProvider)(nil).FetchTvDetails), ctx, id, userId)
}

// FetchTvEpisodeDetails mocks base method.
func (m *MockTmdbProvider) FetchTvEpisodeDetails(ctx context.Context, showId, seasonNumber, episodeNumber uint64, userId uuid.UUID) (*serializers.EpisodeDetailsSerializer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTvEpisodeDetails", ctx, showId, seasonNumber, episodeNumber, userId)
	ret0, _ := ret[0].(*serializers.EpisodeDetailsSerializer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTvEpisodeDetails indicates an expected call of FetchTvEpisodeDetails.
func (mr *MockTmdbProviderMockRecorder) FetchTvEpisodeDetails(ctx, showId, seasonNumber, episodeNumber, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTvEpisodeDetails", reflect.TypeOf((*MockTmdbProvider)(nil).FetchTvEpisodeDetails), ctx, showId, seasonNumber, episodeNumber, userId)
}

// FetchTvSeasonDetails mocks base method.
func (m *MockTmdbProvider) FetchTvSeasonDetails(ctx context.Context, showId, seasonNumber uint64, userId uuid.UUID) (*serializers.SeasonDetailsSerializer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTvSeasonDetails", ctx, showId, seasonNumber, userId)
	ret0, _ := ret[0].(*serializers.SeasonDetailsSerializer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTvSeasonDetails indicates an expected call of FetchTvSeasonDetails.
func (mr *MockTmdbProviderMockRecorder) FetchTvSeasonDetails(ctx, showId, seasonNumber, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTvSeasonDetails", reflect.TypeOf((*MockTmdbProvider)(nil).FetchTvSeasonDetails), ctx, showId, seasonNumber, userId)
}

// SearchMovies mocks base method.
func (m *MockTmdbProvider) SearchMovies(ctx context.Context, query string, page uint64, userId uuid.UUID) (*serializers.PaginationResponse[serializers.SearchMovieSerializer], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMovies", ctx, query, page, userId)
	ret0, _ := ret[0].(*serializers.PaginationResponse[serializers.SearchMovieSerializer])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovies indicates an expected call of SearchMovies.
func (mr *MockTmdbProviderMockRecorder) SearchMovies(ctx, query, page, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovies", reflect.TypeOf((*MockTmdbProvider)(nil).SearchMovies), ctx, query, page, userId)
}

// SearchPeople mocks base method.
func (m *MockTmdbProvider) SearchPeople(ctx context.Context, query string, page uint64) (*serializers.PaginationResponse[serializers.SearchPersonSerializer], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPeople", ctx, query, page)
	ret0, _ := ret[0].(*serializers.PaginationResponse[serializers.SearchPersonSerializer])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPeople indicates an expected call of SearchPeople.
func (mr *MockTmdbProviderMockRecorder) SearchPeople(ctx, query, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPeople", reflect.TypeOf((*MockTmdbProvider)(nil).SearchPeople), ctx, query, page)
}

// SearchSeries mocks base method.
func (m *MockTmdbProvider) SearchSeries(ctx context.Context, query string, page uint64, userId uuid.UUID) (*serializers.PaginationResponse[serializers.SearchSeriesSerializer], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSeries", ctx, query, page, userId)
	ret0, _ := ret[0].(*serializers.PaginationResponse[serializers.SearchSeriesSerializer])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSeries indicates an expected call of SearchSeries.
func (mr *MockTmdbProviderMockRecorder) SearchSeries(ctx, query, page, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSeries", reflect.TypeOf((*MockTmdbProvider)(nil).SearchSeries), ctx, query, page, userId)
}
