name: API
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "api/**"
      - ".github/workflows/api.yaml"
  push:
    branches:
      - master
    paths:
      - "api/**"
      - ".github/workflows/api.yaml"
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  GO_ENV: test

defaults:
  run:
    working-directory: api

jobs:
  linter:
    name: Linter
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: api/go.mod
          cache-dependency-path: api/go.sum
      - name: Docs
        run: make doc-comments
      - name: Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a
        with:
          version: v2.11.3
          working-directory: api

  tests:
    name: Tests
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.4-alpine
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: biinge-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: api/go.mod
          cache-dependency-path: api/go.sum
      - name: Schema
        env:
          PGPASSWORD: postgres
        run: psql -h localhost -U postgres -d biinge-test -f db/schema.sql
      - name: Test
        run: make test:race
      - name: Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: api
