name: iOS
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - "ios/**"
      - ".github/workflows/ios.yaml"
  push:
    branches:
      - master
    paths:
      - "ios/**"
      - ".github/workflows/ios.yaml"
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

defaults:
  run:
    working-directory: ios

jobs:
  linter:
    name: Linter
    permissions:
      contents: read
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: ../.github/scripts/swiftlint.sh
      - name: Lint
        run: make lint SWIFTLINT_ARGS=--reporter=github-actions-logging

  tests:
    name: Tests
    permissions:
      contents: read
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Test
        run: make test
